"use client";

import { Printer, X } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Credential {
  username: string;
  password: string;
  displayName: string;
  email: string;
}

interface TeacherCredentialsSheetProps {
  students: Credential[];
  onClose: () => void;
  organizationName?: string;
}

export function TeacherCredentialsSheet({
  students,
  onClose,
  organizationName = "Math for Business Operations",
}: TeacherCredentialsSheetProps) {
  const handlePrint = () => {
    // Open a fresh window with self-contained HTML so print layout is never
    // constrained by the parent dashboard's DOM nesting or Tailwind classes.
    const win = window.open("", "_blank");
    if (!win) return;

    const cards = students
      .map(
        (s) => `
        <div class="card">
          <div class="card-header">
            <span class="card-name">${s.displayName}</span>
            <span class="card-badge">Student Card</span>
          </div>
          <table class="fields">
            <tr><td class="lbl">URL</td><td class="val">${window.location.origin}</td></tr>
            <tr><td class="lbl">Username</td><td class="val mono">${s.username}</td></tr>
            <tr><td class="lbl">Password</td><td class="val mono pw">${s.password}</td></tr>
          </table>
          <p class="card-note">Keep this card safe. Do not share your password.</p>
        </div>`,
      )
      .join("");

    win.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Student Credentials – ${organizationName}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body   { font-family: system-ui, sans-serif; font-size: 10pt;
             color: #111; background: #fff; padding: 0.4in; }
    h1     { font-size: 16pt; color: #1d4ed8; margin-bottom: 2pt; }
    .sub   { font-size: 8pt; color: #6b7280; margin-bottom: 18pt; }
    .grid  { display: grid; grid-template-columns: 1fr 1fr; gap: 10pt; }
    .card  { border: 1.5pt dashed #d1d5db; border-radius: 5pt;
             padding: 8pt; break-inside: avoid; }
    .card-header { display: flex; justify-content: space-between;
                   align-items: baseline; border-bottom: 1pt solid #e5e7eb;
                   padding-bottom: 5pt; margin-bottom: 6pt; }
    .card-name  { font-size: 11pt; font-weight: 700; }
    .card-badge { font-size: 6.5pt; text-transform: uppercase;
                  letter-spacing: .05em; color: #9ca3af; font-weight: 600; }
    .fields { width: 100%; border-collapse: collapse; font-size: 8pt; }
    .fields tr + tr td { padding-top: 3pt; }
    .lbl   { color: #6b7280; font-weight: 500; width: 56pt; white-space: nowrap; }
    .val   { font-weight: 600; }
    .mono  { font-family: 'Courier New', monospace; }
    .pw    { background: #f3f4f6; padding: 1pt 4pt; border-radius: 2pt; }
    .card-note { margin-top: 7pt; font-size: 7pt; color: #9ca3af; font-style: italic; }
    footer { margin-top: 20pt; text-align: center; font-size: 7pt;
             color: #9ca3af; border-top: 1pt solid #e5e7eb; padding-top: 6pt; }
    @page  { size: letter; margin: 0.5in; }
  </style>
</head>
<body>
  <h1>${organizationName}</h1>
  <p class="sub">Student Login Credentials — ${new Date().toLocaleDateString()}</p>
  <div class="grid">${cards}</div>
  <footer>Generated by Math for Business Operations v2 &bull; ${new Date().toISOString()}</footer>
</body>
</html>`);

    win.document.close();
    win.focus();
    // Give the browser a tick to parse and render before opening the print dialog.
    win.setTimeout(() => {
      win.print();
      win.close();
    }, 250);
  };

  return (
    <div className="fixed inset-0 z-[60] flex flex-col bg-background overflow-hidden animate-in fade-in duration-200">
      <header className="flex items-center justify-between border-b px-6 py-4 bg-background print:hidden">
        <div>
          <h2 className="text-xl font-semibold">Student Credentials Sheet</h2>
          <p className="text-sm text-muted-foreground">Print or download these for your students.</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" className="gap-2" onClick={handlePrint}>
            <Printer className="size-4" />
            Print
          </Button>
          <Button variant="ghost" size="icon" onClick={onClose}>
            <X className="size-4" />
            <span className="sr-only">Close</span>
          </Button>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto bg-muted/20 p-8 print:p-0 print:bg-white print:overflow-visible">
        <div
          className="mx-auto max-w-[8.5in] bg-white p-[0.5in] shadow-sm"
          style={{ minHeight: "11in" }}
        >
          <div className="mb-8 border-b-2 border-primary pb-4">
            <h1 className="text-2xl font-bold text-primary">{organizationName}</h1>
            <p className="text-sm text-muted-foreground">Student Login Credentials &mdash; {new Date().toLocaleDateString()}</p>
          </div>

          <div className="grid grid-cols-2 gap-4 print:grid-cols-2">
            {students.map((student, index) => (
              <div 
                key={index}
                className="border-2 border-dashed border-muted-foreground/30 p-4 rounded-lg space-y-3 break-inside-avoid"
              >
                <div className="flex justify-between items-start border-b pb-2">
                  <div className="font-bold text-lg">{student.displayName}</div>
                  <div className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">Student Card</div>
                </div>
                
                <div className="grid grid-cols-3 gap-2 text-xs">
                  <div className="text-muted-foreground font-medium">URL:</div>
                  <div className="col-span-2 font-mono truncate text-primary">{window.location.origin}</div>
                  
                  <div className="text-muted-foreground font-medium">Username:</div>
                  <div className="col-span-2 font-mono font-bold">{student.username}</div>
                  
                  <div className="text-muted-foreground font-medium">Password:</div>
                  <div className="col-span-2 font-mono font-bold bg-muted/50 px-1 rounded">{student.password}</div>
                </div>

                <div className="pt-2 text-[9px] text-muted-foreground italic leading-tight">
                  Keep this card safe. Do not share your password with others.
                </div>
              </div>
            ))}
          </div>

          <footer className="mt-12 text-center text-[10px] text-muted-foreground border-t pt-4">
            Generated by Math for Business Operations v2 &bull; {new Date().toISOString()}
          </footer>
        </div>
      </main>

    </div>
  );
}
