import type { GlossaryTerm } from './types';

export const GLOSSARY: GlossaryTerm[] = [
  {
    slug: 'quadratic-function',
    term: 'Quadratic Function',
    definition: 'A function of the form f(x) = ax² + bx + c where a ≠ 0, producing a parabolic graph.',
    modules: [1],
    topics: ['quadratic-functions', 'forms'],
    synonyms: ['second-degree polynomial'],
    related: ['parabola', 'vertex-form', 'standard-form'],
  },
  {
    slug: 'parabola',
    term: 'Parabola',
    definition: 'The U-shaped graph of a quadratic function, symmetric about its axis of symmetry.',
    modules: [1],
    topics: ['quadratic-functions', 'graphing'],
    synonyms: [],
    related: ['axis-of-symmetry', 'vertex', 'quadratic-function'],
  },
  {
    slug: 'vertex',
    term: 'Vertex',
    definition: 'The highest or lowest point of a parabola, located at (h, k) in vertex form.',
    modules: [1],
    topics: ['quadratic-functions', 'features'],
    synonyms: [],
    related: ['parabola', 'axis-of-symmetry', 'vertex-form'],
  },
  {
    slug: 'axis-of-symmetry',
    term: 'Axis of Symmetry',
    definition: 'The vertical line x = h that divides a parabola into two mirror images.',
    modules: [1],
    topics: ['quadratic-functions', 'features'],
    synonyms: ['line of symmetry'],
    related: ['parabola', 'vertex'],
  },
  {
    slug: 'vertex-form',
    term: 'Vertex Form',
    definition: 'Quadratic function written as f(x) = a(x - h)² + k, revealing the vertex (h, k).',
    modules: [1],
    topics: ['quadratic-functions', 'forms'],
    synonyms: [],
    related: ['standard-form', 'intercept-form', 'vertex'],
  },
  {
    slug: 'standard-form',
    term: 'Standard Form',
    definition: 'Quadratic function written as f(x) = ax² + bx + c, revealing coefficients.',
    modules: [1],
    topics: ['quadratic-functions', 'forms'],
    synonyms: [],
    related: ['vertex-form', 'intercept-form'],
  },
  {
    slug: 'intercept-form',
    term: 'Intercept Form',
    definition: 'Quadratic function written as f(x) = a(x - p)(x - q), revealing x-intercepts p and q.',
    modules: [1],
    topics: ['quadratic-functions', 'forms'],
    synonyms: ['factored form'],
    related: ['vertex-form', 'standard-form', 'zero-product-property'],
  },
  {
    slug: 'discriminant',
    term: 'Discriminant',
    definition: 'The value b² - 4ac in the quadratic formula that determines the number and type of solutions.',
    modules: [1],
    topics: ['quadratic-equations', 'solving'],
    synonyms: [],
    related: ['quadratic-formula', 'complex-number'],
  },
  {
    slug: 'quadratic-formula',
    term: 'Quadratic Formula',
    definition: 'x = (-b ± √(b² - 4ac)) / 2a, the formula for solving ax² + bx + c = 0.',
    modules: [1],
    topics: ['quadratic-equations', 'solving'],
    synonyms: [],
    related: ['discriminant', 'completing-the-square'],
  },
  {
    slug: 'completing-the-square',
    term: 'Completing the Square',
    definition: 'A method for solving quadratic equations by rewriting in vertex form.',
    modules: [1],
    topics: ['quadratic-equations', 'solving'],
    synonyms: [],
    related: ['vertex-form', 'quadratic-formula'],
  },
  {
    slug: 'zero-product-property',
    term: 'Zero Product Property',
    definition: 'If ab = 0, then a = 0 or b = 0. Used to solve factored quadratic equations.',
    modules: [1, 3],
    topics: ['quadratic-equations', 'solving'],
    synonyms: [],
    related: ['intercept-form', 'factoring'],
  },
  {
    slug: 'imaginary-unit',
    term: 'Imaginary Unit',
    definition: 'The number i where i² = -1, used to define complex numbers.',
    modules: [1],
    topics: ['complex-numbers'],
    synonyms: ['i'],
    related: ['complex-number', 'imaginary-number'],
  },
  {
    slug: 'complex-number',
    term: 'Complex Number',
    definition: 'A number of the form a + bi where a and b are real numbers and i² = -1.',
    modules: [1],
    topics: ['complex-numbers'],
    synonyms: [],
    related: ['imaginary-unit', 'real-number', 'complex-plane'],
  },
  {
    slug: 'complex-plane',
    term: 'Complex Plane',
    definition: 'A coordinate system where the horizontal axis is the real part and vertical is the imaginary part.',
    modules: [1],
    topics: ['complex-numbers'],
    synonyms: [],
    related: ['complex-number', 'argand-diagram'],
  },
  {
    slug: 'polynomial',
    term: 'Polynomial',
    definition: 'An algebraic expression consisting of terms with nonnegative integer exponents.',
    modules: [2],
    topics: ['polynomials', 'definitions'],
    synonyms: [],
    related: ['degree', 'leading-coefficient', 'term'],
  },
  {
    slug: 'degree',
    term: 'Degree',
    definition: 'The highest power of the variable in a polynomial.',
    modules: [2],
    topics: ['polynomials', 'definitions'],
    synonyms: [],
    related: ['polynomial', 'leading-coefficient'],
  },
  {
    slug: 'leading-coefficient',
    term: 'Leading Coefficient',
    definition: 'The coefficient of the term with highest degree in a polynomial.',
    modules: [2],
    topics: ['polynomials', 'definitions'],
    synonyms: [],
    related: ['polynomial', 'degree', 'end-behavior'],
  },
  {
    slug: 'end-behavior',
    term: 'End Behavior',
    definition: 'The direction the graph of a polynomial heads as x approaches ±∞.',
    modules: [2],
    topics: ['polynomial-functions', 'graphing'],
    synonyms: [],
    related: ['degree', 'leading-coefficient'],
  },
  {
    slug: 'turning-point',
    term: 'Turning Point',
    definition: 'A point where a polynomial changes direction from increasing to decreasing or vice versa.',
    modules: [2],
    topics: ['polynomial-functions', 'graphing'],
    synonyms: ['local-extremum'],
    related: ['multiplicity', 'degree'],
  },
  {
    slug: 'multiplicity',
    term: 'Multiplicity',
    definition: 'The number of times a factor appears in a factored polynomial, affecting graph behavior at x-intercepts.',
    modules: [2, 3],
    topics: ['polynomial-functions', 'roots'],
    synonyms: [],
    related: ['zero-product-property', 'root'],
  },
  {
    slug: 'synthetic-division',
    term: 'Synthetic Division',
    definition: 'A shortcut method for dividing polynomials by linear binomials of the form (x - c).',
    modules: [2],
    topics: ['polynomials', 'operations'],
    synonyms: [],
    related: ['long-division', 'remainder-theorem'],
  },
  {
    slug: 'long-division',
    term: 'Long Division',
    definition: 'A method for dividing polynomials by other polynomials.',
    modules: [2],
    topics: ['polynomials', 'operations'],
    synonyms: [],
    related: ['synthetic-division'],
  },
  {
    slug: 'binomial-theorem',
    term: 'Binomial Theorem',
    definition: 'The formula for expanding (a + b)ⁿ using Pascal\'s Triangle.',
    modules: [2],
    topics: ['polynomials', 'operations'],
    synonyms: [],
    related: ['pascals-triangle'],
  },
  {
    slug: 'pascals-triangle',
    term: 'Pascal\'s Triangle',
    definition: 'A triangular array of binomial coefficients where row n gives coefficients for (a + b)ⁿ⁻¹.',
    modules: [2],
    topics: ['polynomials', 'patterns'],
    synonyms: [],
    related: ['binomial-theorem'],
  },
  {
    slug: 'remainder-theorem',
    term: 'Remainder Theorem',
    definition: 'When a polynomial f(x) is divided by (x - c), the remainder equals f(c).',
    modules: [3],
    topics: ['polynomial-equations', 'theorems'],
    synonyms: [],
    related: ['factor-theorem', 'synthetic-division'],
  },
  {
    slug: 'factor-theorem',
    term: 'Factor Theorem',
    definition: '(x - c) is a factor of f(x) if and only if f(c) = 0.',
    modules: [3],
    topics: ['polynomial-equations', 'theorems'],
    synonyms: [],
    related: ['remainder-theorem', 'root'],
  },
  {
    slug: 'fundamental-theorem-of-algebra',
    term: 'Fundamental Theorem of Algebra',
    definition: 'Every polynomial of degree n has exactly n complex roots (counting multiplicity).',
    modules: [3],
    topics: ['polynomial-equations', 'theorems'],
    synonyms: [],
    related: ['complex-number', 'root'],
  },
  {
    slug: 'root',
    term: 'Root',
    definition: 'A value x = r such that f(r) = 0 for a polynomial f(x).',
    modules: [3],
    topics: ['polynomial-equations', 'solutions'],
    synonyms: ['zero'],
    related: ['factor-theorem', 'multiplicity'],
  },
  {
    slug: 'inverse-function',
    term: 'Inverse Function',
    definition: 'A function f⁻¹ such that f(f⁻¹(x)) = x and f⁻¹(f(x)) = x for all x in the domain.',
    modules: [4],
    topics: ['inverse-functions', 'definitions'],
    synonyms: [],
    related: ['one-to-one', 'composition'],
  },
  {
    slug: 'one-to-one',
    term: 'One-to-One Function',
    definition: 'A function where each output corresponds to exactly one input (horizontal line test passes).',
    modules: [4],
    topics: ['inverse-functions', 'definitions'],
    synonyms: ['injective'],
    related: ['horizontal-line-test', 'inverse-function'],
  },
  {
    slug: 'horizontal-line-test',
    term: 'Horizontal Line Test',
    definition: 'A test to determine if a function is one-to-one by checking if any horizontal line intersects its graph more than once.',
    modules: [4],
    topics: ['inverse-functions', 'testing'],
    synonyms: [],
    related: ['one-to-one', 'vertical-line-test'],
  },
  {
    slug: 'radical',
    term: 'Radical',
    definition: 'An expression containing a root symbol, such as √x or ∛x.',
    modules: [4],
    topics: ['radicals', 'expressions'],
    synonyms: ['root'],
    related: ['square-root', 'rational-exponent'],
  },
  {
    slug: 'rational-exponent',
    term: 'Rational Exponent',
    definition: 'An exponent expressed as a fraction, where a^(m/n) = ⁿ√(a^m).',
    modules: [4],
    topics: ['radicals', 'exponents'],
    synonyms: [],
    related: ['radical', 'exponential-function'],
  },
  {
    slug: 'composition-of-functions',
    term: 'Composition of Functions',
    definition: 'Applying one function to the output of another, written as (f ∘ g)(x) = f(g(x)).',
    modules: [4],
    topics: ['inverse-functions', 'operations'],
    synonyms: ['composite function'],
    related: ['inverse-function', 'function'],
  },
  {
    slug: 'exponential-function',
    term: 'Exponential Function',
    definition: 'A function of the form f(x) = a·bˣ where b > 0 and b ≠ 1.',
    modules: [5],
    topics: ['exponential-functions', 'definitions'],
    synonyms: [],
    related: ['logarithm', 'growth', 'decay'],
  },
  {
    slug: 'logarithm',
    term: 'Logarithm',
    definition: 'The exponent y such that bʸ = x, written as log_b(x) = y.',
    modules: [5, 6],
    topics: ['logarithms', 'definitions'],
    synonyms: ['log'],
    related: ['exponential-function', 'common-log', 'natural-log'],
  },
  {
    slug: 'common-log',
    term: 'Common Logarithm',
    definition: 'A logarithm with base 10, written as log(x) or log₁₀(x).',
    modules: [5, 6],
    topics: ['logarithms', 'types'],
    synonyms: [],
    related: ['logarithm', 'natural-log'],
  },
  {
    slug: 'natural-logarithm',
    term: 'Natural Logarithm',
    definition: 'A logarithm with base e, written as ln(x) where e ≈ 2.718.',
    modules: [5, 6],
    topics: ['logarithms', 'types'],
    synonyms: ['ln'],
    related: ['logarithm', 'common-log'],
  },
  {
    slug: 'asymptote',
    term: 'Asymptote',
    definition: 'A line that a graph approaches but never touches as x or y approaches infinity.',
    modules: [5, 6, 7],
    topics: ['function-behavior', 'graphing'],
    synonyms: [],
    related: ['exponential-function', 'logarithmic-function', 'rational-function'],
  },
  {
    slug: 'exponential-growth',
    term: 'Exponential Growth',
    definition: 'Growth modeled by f(t) = a·b^t where b > 1, increasing without bound.',
    modules: [5],
    topics: ['exponential-functions', 'models'],
    synonyms: [],
    related: ['exponential-function', 'exponential-decay'],
  },
  {
    slug: 'exponential-decay',
    term: 'Exponential Decay',
    definition: 'Decay modeled by f(t) = a·b^t where 0 < b < 1, decreasing toward a horizontal asymptote.',
    modules: [5],
    topics: ['exponential-functions', 'models'],
    synonyms: [],
    related: ['exponential-function', 'exponential-growth'],
  },
  {
    slug: 'compound-interest',
    term: 'Compound Interest',
    definition: 'Interest calculated on both the initial principal and accumulated interest.',
    modules: [5],
    topics: ['exponential-functions', 'applications'],
    synonyms: [],
    related: ['exponential-function', 'exponential-growth'],
  },
  {
    slug: 'geometric-sequence',
    term: 'Geometric Sequence',
    definition: 'A sequence where each term is multiplied by a constant ratio r to get the next term.',
    modules: [5],
    topics: ['sequences', 'definitions'],
    synonyms: ['geometric progression'],
    related: ['geometric-series', 'common-ratio'],
  },
  {
    slug: 'geometric-series',
    term: 'Geometric Series',
    definition: 'The sum of terms in a geometric sequence.',
    modules: [5],
    topics: ['sequences', 'series'],
    synonyms: [],
    related: ['geometric-sequence', 'infinite-series'],
  },
  {
    slug: 'change-of-base',
    term: 'Change of Base',
    definition: 'The formula log_b(x) = log_a(x) / log_a(b) for converting between logarithm bases.',
    modules: [6],
    topics: ['logarithms', 'properties'],
    synonyms: [],
    related: ['logarithm', 'log-properties'],
  },
  {
    slug: 'log-properties',
    term: 'Logarithm Properties',
    definition: 'Rules including: log(MN) = log M + log N, log(M/N) = log M - log N, log(M^k) = k·log M.',
    modules: [6],
    topics: ['logarithms', 'properties'],
    synonyms: ['logarithm rules'],
    related: ['logarithm', 'change-of-base'],
  },
  {
    slug: 'logarithmic-function',
    term: 'Logarithmic Function',
    definition: 'The inverse function of an exponential function, written f(x) = log_b(x).',
    modules: [6],
    topics: ['logarithmic-functions', 'definitions'],
    synonyms: [],
    related: ['logarithm', 'exponential-function', 'asymptote'],
  },
  {
    slug: 'rational-function',
    term: 'Rational Function',
    definition: 'A function of the form f(x) = P(x) / Q(x) where P and Q are polynomials and Q(x) ≠ 0.',
    modules: [7],
    topics: ['rational-functions', 'definitions'],
    synonyms: [],
    related: ['asymptote', 'hole', 'domain-restriction'],
  },
  {
    slug: 'vertical-asymptote',
    term: 'Vertical Asymptote',
    definition: 'A vertical line x = a where the function approaches ±∞ as x approaches a.',
    modules: [7],
    topics: ['rational-functions', 'asymptotes'],
    synonyms: [],
    related: ['rational-function', 'horizontal-asymptote'],
  },
  {
    slug: 'horizontal-asymptote',
    term: 'Horizontal Asymptote',
    definition: 'A horizontal line y = b that the graph approaches as x → ±∞.',
    modules: [7],
    topics: ['rational-functions', 'asymptotes'],
    synonyms: [],
    related: ['rational-function', 'vertical-asymptote'],
  },
  {
    slug: 'hole',
    term: 'Hole',
    definition: 'A point (a, b) removed from the graph of a rational function when a factor cancels.',
    modules: [7],
    topics: ['rational-functions', 'features'],
    synonyms: ['point of discontinuity'],
    related: ['rational-function', 'domain-restriction'],
  },
  {
    slug: 'domain-restriction',
    term: 'Domain Restriction',
    definition: 'Values excluded from the domain of a function, such as where denominator = 0.',
    modules: [7],
    topics: ['rational-functions', 'definitions'],
    synonyms: [],
    related: ['rational-function', 'hole'],
  },
  {
    slug: 'population',
    term: 'Population',
    definition: 'The entire set of individuals or objects about which information is sought.',
    modules: [8],
    topics: ['statistics', 'definitions'],
    synonyms: [],
    related: ['sample', 'census'],
  },
  {
    slug: 'sample',
    term: 'Sample',
    definition: 'A subset of the population selected for study to make inferences about the population.',
    modules: [8],
    topics: ['statistics', 'definitions'],
    synonyms: [],
    related: ['population', 'sampling-method'],
  },
  {
    slug: 'bias',
    term: 'Statistical Bias',
    definition: 'A systematic tendency to favor certain outcomes or misrepresent the population.',
    modules: [8],
    topics: ['statistics', 'data-quality'],
    synonyms: [],
    related: ['population', 'sample', 'random-sample'],
  },
  {
    slug: 'mean',
    term: 'Mean',
    definition: 'The arithmetic average of a set of values, calculated as sum divided by count.',
    modules: [8],
    topics: ['statistics', 'measures-of-center'],
    synonyms: ['average', 'arithmetic-mean'],
    related: ['median', 'mode', 'standard-deviation'],
  },
  {
    slug: 'median',
    term: 'Median',
    definition: 'The middle value in an ordered data set, or the average of the two middle values.',
    modules: [8],
    topics: ['statistics', 'measures-of-center'],
    synonyms: [],
    related: ['mean', 'mode', 'quartile'],
  },
  {
    slug: 'mode',
    term: 'Mode',
    definition: 'The value(s) that appear most frequently in a data set.',
    modules: [8],
    topics: ['statistics', 'measures-of-center'],
    synonyms: [],
    related: ['mean', 'median'],
  },
  {
    slug: 'standard-deviation',
    term: 'Standard Deviation',
    definition: 'A measure of spread calculated as the square root of the variance.',
    modules: [8],
    topics: ['statistics', 'measures-of-spread'],
    synonyms: ['sigma', 'σ'],
    related: ['variance', 'mean', 'normal-distribution'],
  },
  {
    slug: 'variance',
    term: 'Variance',
    definition: 'The average of squared deviations from the mean, measuring data spread.',
    modules: [8],
    topics: ['statistics', 'measures-of-spread'],
    synonyms: [],
    related: ['standard-deviation', 'mean'],
  },
  {
    slug: 'normal-distribution',
    term: 'Normal Distribution',
    definition: 'A symmetric, bell-shaped probability distribution characterized by mean μ and standard deviation σ.',
    modules: [8],
    topics: ['statistics', 'distributions'],
    synonyms: ['gaussian-distribution', 'bell-curve'],
    related: ['z-score', 'standard-deviation', 'mean'],
  },
  {
    slug: 'z-score',
    term: 'Z-Score',
    definition: 'The number of standard deviations a value is from the mean: z = (x - μ) / σ.',
    modules: [8],
    topics: ['statistics', 'standardization'],
    synonyms: ['standard-score'],
    related: ['normal-distribution', 'standard-deviation'],
  },
  {
    slug: 'confidence-interval',
    term: 'Confidence Interval',
    definition: 'A range of values, derived from sample data, that likely contains the population parameter.',
    modules: [8],
    topics: ['statistics', 'inference'],
    synonyms: [],
    related: ['population', 'sample', 'margin-of-error'],
  },
  {
    slug: 'angle',
    term: 'Angle',
    definition: 'A figure formed by two rays sharing a common endpoint, measured in degrees or radians.',
    modules: [9],
    topics: ['trigonometry', 'basics'],
    synonyms: [],
    related: ['degree', 'radian'],
  },
  {
    slug: 'radian',
    term: 'Radian',
    definition: 'The angle subtended by an arc equal in length to the radius, where 2π radians = 360°.',
    modules: [9],
    topics: ['trigonometry', 'angle-measure'],
    synonyms: [],
    related: ['degree-angle', 'unit-circle'],
  },
  {
    slug: 'degree-angle',
    term: 'Degree',
    definition: 'A unit of angle measure where 360° = one full rotation.',
    modules: [9],
    topics: ['trigonometry', 'angle-measure'],
    synonyms: [],
    related: ['radian', 'angle'],
  },
  {
    slug: 'unit-circle',
    term: 'Unit Circle',
    definition: 'A circle with radius 1 centered at the origin, used to define trigonometric functions.',
    modules: [9],
    topics: ['trigonometry', 'foundations'],
    synonyms: [],
    related: ['sine', 'cosine', 'radian'],
  },
  {
    slug: 'sine',
    term: 'Sine',
    definition: 'For angle θ on the unit circle, sin(θ) = y-coordinate of the intersection point.',
    modules: [9],
    topics: ['trigonometric-functions', 'definitions'],
    synonyms: ['sin'],
    related: ['cosine', 'tangent', 'unit-circle'],
  },
  {
    slug: 'cosine',
    term: 'Cosine',
    definition: 'For angle θ on the unit circle, cos(θ) = x-coordinate of the intersection point.',
    modules: [9],
    topics: ['trigonometric-functions', 'definitions'],
    synonyms: ['cos'],
    related: ['sine', 'tangent', 'unit-circle'],
  },
  {
    slug: 'tangent',
    term: 'Tangent',
    definition: 'For angle θ, tan(θ) = sin(θ) / cos(θ), or the slope of the terminal side on the unit circle.',
    modules: [9],
    topics: ['trigonometric-functions', 'definitions'],
    synonyms: ['tan'],
    related: ['sine', 'cosine', 'slope'],
  },
  {
    slug: 'period',
    term: 'Period',
    definition: 'The horizontal distance for a periodic function to complete one full cycle.',
    modules: [9],
    topics: ['trigonometric-functions', 'properties'],
    synonyms: [],
    related: ['amplitude', 'periodic-function', 'frequency'],
  },
  {
    slug: 'amplitude',
    term: 'Amplitude',
    definition: 'Half the distance between the maximum and minimum values of a periodic function.',
    modules: [9],
    topics: ['trigonometric-functions', 'properties'],
    synonyms: [],
    related: ['period', 'midline', 'sine', 'cosine'],
  },
  {
    slug: 'midline',
    term: 'Midline',
    definition: 'The horizontal line equidistant between the maximum and minimum of a periodic function.',
    modules: [9],
    topics: ['trigonometric-functions', 'properties'],
    synonyms: ['vertical-shift'],
    related: ['amplitude', 'period', 'sine', 'cosine'],
  },
  {
    slug: 'phase-shift',
    term: 'Phase Shift',
    definition: 'The horizontal displacement of a periodic function from its standard position.',
    modules: [9],
    topics: ['trigonometric-functions', 'transformations'],
    synonyms: ['horizontal-shift'],
    related: ['period', 'amplitude', 'vertical-shift'],
  },
  {
    slug: 'periodic-function',
    term: 'Periodic Function',
    definition: 'A function that repeats its values at regular intervals (its period).',
    modules: [9],
    topics: ['trigonometric-functions', 'definitions'],
    synonyms: [],
    related: ['period', 'sine', 'cosine'],
  },
  {
    slug: 'inverse-trigonometric-function',
    term: 'Inverse Trigonometric Function',
    definition: 'The inverse of a trigonometric function, such as arcsin, arccos, or arctan.',
    modules: [9],
    topics: ['trigonometric-functions', 'inverse'],
    synonyms: ['arcsin', 'arccos', 'arctan'],
    related: ['sine', 'cosine', 'tangent', 'restricted-domain'],
  },
];

export function getGlossaryTermBySlug(slug: string): GlossaryTerm | undefined {
  return GLOSSARY.find((term) => term.slug === slug);
}

export function getGlossaryTermsByModule(moduleNumber: number): GlossaryTerm[] {
  return GLOSSARY.filter((term) => term.modules.includes(moduleNumber));
}

export function getAllGlossaryModules(): number[] {
  const modules = new Set<number>();
  GLOSSARY.forEach((term) => term.modules.forEach((m) => modules.add(m)));
  return Array.from(modules).sort((a, b) => a - b);
}

export function getAllGlossaryTopics(): string[] {
  const topics = new Set<string>();
  GLOSSARY.forEach((term) => term.topics.forEach((t) => topics.add(t)));
  return Array.from(topics).sort();
}
