// Synthetic fixtures for testing only
// Uses synthetic placeholder content; no proprietary maps, descriptors, or curriculum data.

import type { KnowledgeSpace } from './types';

// ---------------------------------------------------------------------------
// Math-like synthetic fixture
// ---------------------------------------------------------------------------

export const syntheticMathFixture: KnowledgeSpace = {
  nodes: [
    {
      id: 'math.im3.domain',
      kind: 'domain',
      title: 'Integrated Math 3 (synthetic)',
      domain: 'math.im3',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
      metadata: { version: 'v1', description: 'Synthetic math domain for testing' },
    },
    {
      id: 'math.im3.content-group.m1',
      kind: 'content_group',
      title: 'Module 1: Quadratic Functions (synthetic)',
      domain: 'math.im3',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
      metadata: { module: '1' },
    },
    {
      id: 'math.im3.unit.m1.l2',
      kind: 'instructional_unit',
      title: 'Lesson 1.2: Solving Quadratics by Factoring (synthetic)',
      domain: 'math.im3',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
      metadata: { module: '1', lesson: '2' },
    },
    {
      id: 'math.im3.skill.m1.l2.solve-quadratic-by-factoring',
      kind: 'skill',
      title: 'Solve quadratic equations by factoring',
      domain: 'math.im3',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
      metadata: { difficulty: 0.5, bloomsLevel: 'apply' },
    },
    {
      id: 'math.im3.skill.m1.l2.identify-roots',
      kind: 'skill',
      title: 'Identify roots of a quadratic from its factored form',
      domain: 'math.im3',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
      metadata: { difficulty: 0.4, bloomsLevel: 'comprehend' },
    },
    {
      id: 'math.im3.standard.ccss.hsa.rei.b.4b',
      kind: 'standard',
      title: 'CCSS.MATH.CONTENT.HSA.REI.B.4.B — Solve quadratic equations (synthetic)',
      domain: 'math.im3',
      sourceRefs: ['synthetic-ccss'],
      reviewStatus: 'draft',
      metadata: { framework: 'CCSS', gradeLevel: 'HS' },
    },
    {
      id: 'math.im3.worked-example.m1.l2.factoring-basic',
      kind: 'worked_example',
      title: 'Factoring x² + 5x + 6',
      domain: 'math.im3',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
      metadata: { type: 'example' },
    },
    {
      id: 'math.im3.task-blueprint.m1.l2.factoring-drill',
      kind: 'task_blueprint',
      title: 'Factoring drill — random trinomials',
      domain: 'math.im3',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
      metadata: { practiceMode: 'independent' },
      independentPracticeReady: true,
    },
    {
      id: 'math.im3.generator.quadratic-factoring',
      kind: 'generator',
      title: 'Quadratic Factoring Generator',
      domain: 'math.im3',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
      metadata: { engine: 'algebraic-generator', variantCount: 50 },
    },
    {
      id: 'math.im3.renderer.coordinate-plane',
      kind: 'renderer',
      title: 'Coordinate Plane Renderer',
      domain: 'math.im3',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
      metadata: { rendererType: 'graphing-explorer' },
    },
  ],
  edges: [
    {
      id: 'math.im3.edge.contains-m1',
      type: 'contains',
      sourceId: 'math.im3.domain',
      targetId: 'math.im3.content-group.m1',
      weight: 1,
      confidence: 'high',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
    },
    {
      id: 'math.im3.edge.contains-l2',
      type: 'contains',
      sourceId: 'math.im3.content-group.m1',
      targetId: 'math.im3.unit.m1.l2',
      weight: 1,
      confidence: 'high',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
    },
    {
      id: 'math.im3.edge.appears-in-l2-factoring',
      type: 'appears_in_context',
      sourceId: 'math.im3.skill.m1.l2.solve-quadratic-by-factoring',
      targetId: 'math.im3.unit.m1.l2',
      weight: 1,
      confidence: 'high',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
    },
    {
      id: 'math.im3.edge.align-std-factoring',
      type: 'aligned_to_standard',
      sourceId: 'math.im3.skill.m1.l2.solve-quadratic-by-factoring',
      targetId: 'math.im3.standard.ccss.hsa.rei.b.4b',
      weight: 1,
      confidence: 'high',
      sourceRefs: ['synthetic-ccss'],
      reviewStatus: 'draft',
    },
    {
      id: 'math.im3.edge.align-std-roots',
      type: 'aligned_to_standard',
      sourceId: 'math.im3.skill.m1.l2.identify-roots',
      targetId: 'math.im3.standard.ccss.hsa.rei.b.4b',
      weight: 0.9,
      confidence: 'high',
      sourceRefs: ['synthetic-ccss'],
      reviewStatus: 'draft',
    },
    {
      id: 'math.im3.edge.align-example-factoring',
      type: 'aligned_to_standard',
      sourceId: 'math.im3.worked-example.m1.l2.factoring-basic',
      targetId: 'math.im3.standard.ccss.hsa.rei.b.4b',
      weight: 0.8,
      confidence: 'high',
      sourceRefs: ['synthetic-ccss'],
      reviewStatus: 'draft',
    },
    {
      id: 'math.im3.edge.align-blueprint-factoring',
      type: 'aligned_to_standard',
      sourceId: 'math.im3.task-blueprint.m1.l2.factoring-drill',
      targetId: 'math.im3.standard.ccss.hsa.rei.b.4b',
      weight: 0.8,
      confidence: 'high',
      sourceRefs: ['synthetic-ccss'],
      reviewStatus: 'draft',
    },
    {
      id: 'math.im3.edge.prereq-roots-factoring',
      type: 'prerequisite_for',
      sourceId: 'math.im3.skill.m1.l2.identify-roots',
      targetId: 'math.im3.skill.m1.l2.solve-quadratic-by-factoring',
      weight: 0.8,
      confidence: 'high',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
    },
    {
      id: 'math.im3.edge.generated-by-drill',
      type: 'generated_by',
      sourceId: 'math.im3.task-blueprint.m1.l2.factoring-drill',
      targetId: 'math.im3.generator.quadratic-factoring',
      weight: 1,
      confidence: 'high',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
    },
  ],
};

// ---------------------------------------------------------------------------
// English/GSE-like synthetic fixture
// ---------------------------------------------------------------------------

export const syntheticEnglishGseFixture: KnowledgeSpace = {
  nodes: [
    {
      id: 'english.gse.domain',
      kind: 'domain',
      title: 'English GSE (synthetic)',
      domain: 'english.gse',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
      metadata: { version: 'v1', framework: 'GSE' },
    },
    {
      id: 'english.gse.skill.b1.reading.identify-main-idea.short-text',
      kind: 'skill',
      title: 'Identify the main idea in short texts',
      domain: 'english.gse',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
      metadata: {
        gseRange: '43-50',
        cefr: 'B1',
        modality: 'reading',
        languageFunction: 'comprehension',
      },
    },
    {
      id: 'english.gse.skill.b1.reading.infer-meaning-context',
      kind: 'skill',
      title: 'Infer meaning of unfamiliar words from context',
      domain: 'english.gse',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
      metadata: {
        gseRange: '45-52',
        cefr: 'B1',
        modality: 'reading',
        languageFunction: 'comprehension',
      },
    },
  ],
  edges: [
    {
      id: 'english.gse.edge.prereq-context-to-main',
      type: 'prerequisite_for',
      sourceId: 'english.gse.skill.b1.reading.infer-meaning-context',
      targetId: 'english.gse.skill.b1.reading.identify-main-idea.short-text',
      weight: 0.6,
      confidence: 'medium',
      sourceRefs: ['synthetic'],
      reviewStatus: 'draft',
    },
  ],
};
