export type AccountType = 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';
export type NormalBalance = 'debit' | 'credit';
export type StatementPlacement = 'balance-sheet' | 'income-statement' | 'equity-statement';

export interface PracticeAccount {
  id: string;
  label: string;
  accountType: AccountType;
  normalBalance: NormalBalance;
  statementPlacement: StatementPlacement;
  contraOf?: string;
  retailApplicable: boolean;
  subcategory: string;
  commonConfusionPairs?: string[];
}

export const practiceAccounts = [
  {
    id: 'cash',
    label: 'Cash',
    accountType: 'asset',
    normalBalance: 'debit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'current-asset',
    commonConfusionPairs: ['accounts-receivable', 'prepaid-rent'],
  },
  {
    id: 'accounts-receivable',
    label: 'Accounts Receivable',
    accountType: 'asset',
    normalBalance: 'debit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'current-asset',
    commonConfusionPairs: ['allowance-for-doubtful-accounts', 'notes-receivable'],
  },
  {
    id: 'notes-receivable',
    label: 'Notes Receivable',
    accountType: 'asset',
    normalBalance: 'debit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'current-asset',
    commonConfusionPairs: ['accounts-receivable'],
  },
  {
    id: 'supplies',
    label: 'Supplies',
    accountType: 'asset',
    normalBalance: 'debit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'current-asset',
    commonConfusionPairs: ['supplies-expense', 'prepaid-rent'],
  },
  {
    id: 'prepaid-insurance',
    label: 'Prepaid Insurance',
    accountType: 'asset',
    normalBalance: 'debit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'current-asset',
    commonConfusionPairs: ['insurance-expense'],
  },
  {
    id: 'prepaid-rent',
    label: 'Prepaid Rent',
    accountType: 'asset',
    normalBalance: 'debit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'current-asset',
    commonConfusionPairs: ['rent-expense'],
  },
  {
    id: 'merchandise-inventory',
    label: 'Merchandise Inventory',
    accountType: 'asset',
    normalBalance: 'debit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'inventory',
    commonConfusionPairs: ['supplies', 'cost-of-goods-sold'],
  },
  {
    id: 'equipment',
    label: 'Equipment',
    accountType: 'asset',
    normalBalance: 'debit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'long-term-asset',
    commonConfusionPairs: ['accumulated-depreciation-equipment', 'land'],
  },
  {
    id: 'buildings',
    label: 'Buildings',
    accountType: 'asset',
    normalBalance: 'debit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'long-term-asset',
    commonConfusionPairs: ['accumulated-depreciation-buildings'],
  },
  {
    id: 'land',
    label: 'Land',
    accountType: 'asset',
    normalBalance: 'debit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'long-term-asset',
    commonConfusionPairs: ['buildings'],
  },
  {
    id: 'accumulated-depreciation-equipment',
    label: 'Accumulated Depreciation - Equipment',
    accountType: 'asset',
    normalBalance: 'credit',
    statementPlacement: 'balance-sheet',
    contraOf: 'equipment',
    retailApplicable: true,
    subcategory: 'contra-asset',
    commonConfusionPairs: ['depreciation-expense'],
  },
  {
    id: 'accumulated-depreciation-buildings',
    label: 'Accumulated Depreciation - Buildings',
    accountType: 'asset',
    normalBalance: 'credit',
    statementPlacement: 'balance-sheet',
    contraOf: 'buildings',
    retailApplicable: true,
    subcategory: 'contra-asset',
    commonConfusionPairs: ['depreciation-expense'],
  },
  {
    id: 'allowance-for-doubtful-accounts',
    label: 'Allowance for Doubtful Accounts',
    accountType: 'asset',
    normalBalance: 'credit',
    statementPlacement: 'balance-sheet',
    contraOf: 'accounts-receivable',
    retailApplicable: true,
    subcategory: 'contra-asset',
    commonConfusionPairs: ['accounts-receivable'],
  },
  {
    id: 'accounts-payable',
    label: 'Accounts Payable',
    accountType: 'liability',
    normalBalance: 'credit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'current-liability',
    commonConfusionPairs: ['notes-payable-current'],
  },
  {
    id: 'salaries-payable',
    label: 'Salaries Payable',
    accountType: 'liability',
    normalBalance: 'credit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'current-liability',
    commonConfusionPairs: ['salaries-expense'],
  },
  {
    id: 'interest-payable',
    label: 'Interest Payable',
    accountType: 'liability',
    normalBalance: 'credit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'current-liability',
    commonConfusionPairs: ['interest-expense'],
  },
  {
    id: 'sales-tax-payable',
    label: 'Sales Tax Payable',
    accountType: 'liability',
    normalBalance: 'credit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'current-liability',
    commonConfusionPairs: ['sales-revenue'],
  },
  {
    id: 'notes-payable',
    label: 'Notes Payable',
    accountType: 'liability',
    normalBalance: 'credit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'long-term-liability',
    commonConfusionPairs: ['notes-receivable'],
  },
  {
    id: 'unearned-revenue',
    label: 'Unearned Revenue',
    accountType: 'liability',
    normalBalance: 'credit',
    statementPlacement: 'balance-sheet',
    retailApplicable: true,
    subcategory: 'current-liability',
    commonConfusionPairs: ['service-revenue', 'sales-revenue'],
  },
  {
    id: 'common-stock',
    label: 'Common Stock',
    accountType: 'equity',
    normalBalance: 'credit',
    statementPlacement: 'equity-statement',
    retailApplicable: true,
    subcategory: 'contributed-capital',
    commonConfusionPairs: ['retained-earnings', 'service-revenue'],
  },
  {
    id: 'retained-earnings',
    label: 'Retained Earnings',
    accountType: 'equity',
    normalBalance: 'credit',
    statementPlacement: 'equity-statement',
    retailApplicable: true,
    subcategory: 'earned-capital',
    commonConfusionPairs: ['common-stock', 'net-income'],
  },
  {
    id: 'dividends',
    label: 'Dividends',
    accountType: 'equity',
    normalBalance: 'debit',
    statementPlacement: 'equity-statement',
    retailApplicable: true,
    subcategory: 'equity-adjustment',
    commonConfusionPairs: ['withdrawals'],
  },
  {
    id: 'withdrawals',
    label: 'Withdrawals',
    accountType: 'equity',
    normalBalance: 'debit',
    statementPlacement: 'equity-statement',
    retailApplicable: false,
    subcategory: 'equity-adjustment',
    commonConfusionPairs: ['dividends'],
  },
  {
    id: 'treasury-stock',
    label: 'Treasury Stock',
    accountType: 'equity',
    normalBalance: 'debit',
    statementPlacement: 'equity-statement',
    retailApplicable: true,
    subcategory: 'equity-adjustment',
    commonConfusionPairs: ['common-stock'],
  },
  {
    id: 'service-revenue',
    label: 'Service Revenue',
    accountType: 'revenue',
    normalBalance: 'credit',
    statementPlacement: 'income-statement',
    retailApplicable: false,
    subcategory: 'operating-revenue',
    commonConfusionPairs: ['sales-revenue', 'unearned-revenue'],
  },
  {
    id: 'consulting-revenue',
    label: 'Consulting Revenue',
    accountType: 'revenue',
    normalBalance: 'credit',
    statementPlacement: 'income-statement',
    retailApplicable: false,
    subcategory: 'operating-revenue',
    commonConfusionPairs: ['service-revenue'],
  },
  {
    id: 'rent-revenue',
    label: 'Rent Revenue',
    accountType: 'revenue',
    normalBalance: 'credit',
    statementPlacement: 'income-statement',
    retailApplicable: false,
    subcategory: 'other-revenue',
    commonConfusionPairs: ['rent-expense'],
  },
  {
    id: 'interest-revenue',
    label: 'Interest Revenue',
    accountType: 'revenue',
    normalBalance: 'credit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'other-revenue',
    commonConfusionPairs: ['interest-expense'],
  },
  {
    id: 'sales-revenue',
    label: 'Sales Revenue',
    accountType: 'revenue',
    normalBalance: 'credit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-revenue',
    commonConfusionPairs: ['service-revenue', 'sales-discounts'],
  },
  {
    id: 'sales-discounts',
    label: 'Sales Discounts',
    accountType: 'revenue',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    contraOf: 'sales-revenue',
    subcategory: 'contra-revenue',
    commonConfusionPairs: ['sales-returns-and-allowances'],
  },
  {
    id: 'sales-returns-and-allowances',
    label: 'Sales Returns and Allowances',
    accountType: 'revenue',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    contraOf: 'sales-revenue',
    subcategory: 'contra-revenue',
    commonConfusionPairs: ['sales-discounts'],
  },
  {
    id: 'cost-of-goods-sold',
    label: 'Cost of Goods Sold',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-expense',
    commonConfusionPairs: ['merchandise-inventory'],
  },
  {
    id: 'freight-in',
    label: 'Freight In',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'merchandising-expense',
    commonConfusionPairs: ['freight-out'],
  },
  {
    id: 'freight-out',
    label: 'Freight Out',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'merchandising-expense',
    commonConfusionPairs: ['freight-in'],
  },
  {
    id: 'salaries-expense',
    label: 'Salaries Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-expense',
    commonConfusionPairs: ['salaries-payable'],
  },
  {
    id: 'rent-expense',
    label: 'Rent Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-expense',
    commonConfusionPairs: ['prepaid-rent'],
  },
  {
    id: 'insurance-expense',
    label: 'Insurance Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-expense',
    commonConfusionPairs: ['prepaid-insurance'],
  },
  {
    id: 'supplies-expense',
    label: 'Supplies Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-expense',
    commonConfusionPairs: ['supplies'],
  },
  {
    id: 'utilities-expense',
    label: 'Utilities Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-expense',
    commonConfusionPairs: ['cash'],
  },
  {
    id: 'advertising-expense',
    label: 'Advertising Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-expense',
    commonConfusionPairs: ['prepaid-advertising'],
  },
  {
    id: 'depreciation-expense',
    label: 'Depreciation Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-expense',
    commonConfusionPairs: ['accumulated-depreciation-equipment', 'accumulated-depreciation-buildings'],
  },
  {
    id: 'bad-debt-expense',
    label: 'Bad Debt Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-expense',
    commonConfusionPairs: ['allowance-for-doubtful-accounts'],
  },
  {
    id: 'interest-expense',
    label: 'Interest Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'other-expense',
    commonConfusionPairs: ['interest-revenue'],
  },
  {
    id: 'repairs-expense',
    label: 'Repairs Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-expense',
    commonConfusionPairs: ['equipment'],
  },
  {
    id: 'office-supplies-expense',
    label: 'Office Supplies Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-expense',
    commonConfusionPairs: ['supplies'],
  },
  {
    id: 'miscellaneous-expense',
    label: 'Miscellaneous Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    statementPlacement: 'income-statement',
    retailApplicable: true,
    subcategory: 'operating-expense',
    commonConfusionPairs: ['miscellaneous-revenue'],
  },
] as const satisfies readonly PracticeAccount[];

export type PracticeAccountRecord = (typeof practiceAccounts)[number];

const accountById = new Map<string, PracticeAccountRecord>(practiceAccounts.map((account) => [account.id, account]));

export function getAccountById(accountId: string) {
  return accountById.get(accountId);
}

export function byType(accountType: AccountType) {
  return practiceAccounts.filter((account) => account.accountType === accountType);
}

export function byStatement(statementPlacement: StatementPlacement) {
  return practiceAccounts.filter((account) => account.statementPlacement === statementPlacement);
}

export function byNormalBalance(normalBalance: NormalBalance) {
  return practiceAccounts.filter((account) => account.normalBalance === normalBalance);
}

export function isContra(accountOrId: PracticeAccount | PracticeAccountRecord | string) {
  const account =
    typeof accountOrId === 'string' ? getAccountById(accountOrId) : accountOrId;

  return Boolean(account && 'contraOf' in account && account.contraOf);
}
