export const E2E_SEED_KEY = 'e2e-seed-v1';

export const SEL = {
  studentDashboard: 'student-dashboard',
  studentDashboardLessonList: 'student-dashboard-lesson-list',
  studentDashboardLessonLink: 'student-dashboard-lesson-link',
  studentDashboardHeading: 'student-dashboard-heading',
  loginForm: 'login-form',
  loginUsername: 'login-username',
  loginPassword: 'login-password',
  loginSubmit: 'login-submit',
  loginError: 'login-error',
  appShell: 'app-shell',
  logoutButton: 'logout-button',
  userMenu: 'user-menu',
  lessonRenderer: 'lesson-renderer',
  lessonHeader: 'lesson-header',
  lessonTitle: 'lesson-title',
  phaseStepper: 'phase-stepper',
  phaseStepperDot: 'phase-stepper-dot',
  phaseCompleteButton: 'phase-complete-button',
  phaseCompleteStatus: 'phase-complete-status',
  lessonCompleteScreen: 'lesson-complete-screen',
  lessonCompleteContinueBtn: 'lesson-complete-continue-btn',
  deactivatedLoginError: 'deactivated-login-error',
} as const;
