import type { ProblemFamilyInput } from '@math-platform/practice-core';

export const MODULE4_PROBLEM_FAMILIES: ProblemFamilyInput[] = [
  // Operations on Functions (HSF-BF.A.1)
  {
    problemFamilyId: "step-by-step-solver:function-operations",
    componentKey: "step-by-step-solver",
    displayName: "Operations on Functions",
    description: "Find sums, differences, products, quotients of functions",
    objectiveIds: ["HSF-BF.A.1"],
    difficulty: "standard",
    metadata: { module: 4, topic: "function-operations" },
  },
  {
    problemFamilyId: "step-by-step-solver:function-compositions",
    componentKey: "step-by-step-solver",
    displayName: "Composition of Functions",
    description: "Find compositions of functions and evaluate them",
    objectiveIds: ["HSF-BF.A.1", "HSF-BF.B.3"],
    difficulty: "challenging",
    metadata: { module: 4, topic: "function-compositions" },
  },
  // Inverse Functions (HSF-BF.B.4)
  {
    problemFamilyId: "step-by-step-solver:find-inverse-functions",
    componentKey: "step-by-step-solver",
    displayName: "Find Inverse Functions",
    description: "Find inverses of functions and verify using composition",
    objectiveIds: ["HSF-BF.B.4"],
    difficulty: "standard",
    metadata: { module: 4, topic: "inverse-functions" },
  },
  {
    problemFamilyId: "graphing-explorer:inverse-functions",
    componentKey: "graphing-explorer",
    displayName: "Explore Inverse Functions",
    description: "Explore inverse functions graphically using the horizontal line test",
    objectiveIds: ["HSF-BF.B.4"],
    difficulty: "standard",
    metadata: { module: 4, topic: "inverse-functions" },
  },
  // Radical Functions (N-RN.A.1, N-RN.A.2, HSF-IF.C.7a)
  {
    problemFamilyId: "step-by-step-solver:nth-roots-rational-exponents",
    componentKey: "step-by-step-solver",
    displayName: "Nth Roots and Rational Exponents",
    description: "Simplify expressions involving radicals and rational exponents",
    objectiveIds: ["N-RN.A.1", "N-RN.A.2"],
    difficulty: "standard",
    metadata: { module: 4, topic: "radicals" },
  },
  {
    problemFamilyId: "step-by-step-solver:radical-expressions",
    componentKey: "step-by-step-solver",
    displayName: "Simplify Radical Expressions",
    description: "Simplify radical expressions using properties of radicals",
    objectiveIds: ["N-RN.A.1", "N-RN.A.2"],
    difficulty: "standard",
    metadata: { module: 4, topic: "radicals" },
  },
  {
    problemFamilyId: "graphing-explorer:square-root-functions",
    componentKey: "graphing-explorer",
    displayName: "Graph Square Root Functions",
    description: "Graph square root functions and identify key features",
    objectiveIds: ["HSF-IF.C.7a", "HSF-IF.B.4"],
    difficulty: "standard",
    metadata: { module: 4, topic: "radical-functions" },
  },
  {
    problemFamilyId: "graphing-explorer:cube-root-functions",
    componentKey: "graphing-explorer",
    displayName: "Graph Cube Root Functions",
    description: "Graph cube root functions and compare to square root functions",
    objectiveIds: ["HSF-IF.C.7a"],
    difficulty: "standard",
    metadata: { module: 4, topic: "radical-functions" },
  },
  // Solving Radical Equations
  {
    problemFamilyId: "step-by-step-solver:solve-radical-equations",
    componentKey: "step-by-step-solver",
    displayName: "Solve Radical Equations",
    description: "Solve radical equations and identify extraneous solutions",
    objectiveIds: ["N-RN.A.2"],
    difficulty: "standard",
    metadata: { module: 4, topic: "radical-equations" },
  },
  {
    problemFamilyId: "graphing-explorer:solve-radical-equations",
    componentKey: "graphing-explorer",
    displayName: "Solve Radical Equations by Graphing",
    description: "Solve radical equations by graphing and finding intersections",
    objectiveIds: ["N-RN.A.2"],
    difficulty: "standard",
    metadata: { module: 4, topic: "radical-equations" },
  },
  // Transformations (HSF-BF.B.3)
  {
    problemFamilyId: "graphing-explorer:function-transformations",
    componentKey: "graphing-explorer",
    displayName: "Function Transformations",
    description: "Explore effects of transformations on function graphs",
    objectiveIds: ["HSF-BF.B.3"],
    difficulty: "standard",
    metadata: { module: 4, topic: "transformations" },
  },
  // Comprehension
  {
    problemFamilyId: "comprehension-quiz:inverse-radical-vocabulary",
    componentKey: "comprehension-quiz",
    displayName: "Inverse and Radical Vocabulary",
    description: "Assess understanding of inverse function and radical terminology",
    objectiveIds: ["HSF-BF.B.4", "N-RN.A.1"],
    difficulty: "introductory",
    metadata: { module: 4, topic: "vocabulary" },
  },
];