import fs from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';

import ts from 'typescript';

type ExportMap = Record<string, unknown>;

const SOURCE_EXPORTS: Array<{ relativePath: string; exportNames: string[] }> = [
  { relativePath: 'supabase/seed/unit1/lesson-01.ts', exportNames: ['LESSON_01_SEED_DATA'] },
  { relativePath: 'supabase/seed/unit1/lesson-02.ts', exportNames: ['LESSON_02_SEED_DATA'] },
  { relativePath: 'supabase/seed/unit1/lesson-03.ts', exportNames: ['LESSON_03_SEED_DATA'] },
  { relativePath: 'supabase/seed/unit1/lesson-04.ts', exportNames: ['LESSON_04_SEED_DATA'] },
  { relativePath: 'supabase/seed/unit1/lesson-05.ts', exportNames: ['LESSON_05_SEED_DATA'] },
  { relativePath: 'supabase/seed/unit1/lesson-06.ts', exportNames: ['LESSON_06_SEED_DATA'] },
  { relativePath: 'supabase/seed/unit1/lesson-07.ts', exportNames: ['LESSON_07_SEED_DATA'] },
  {
    relativePath: 'supabase/seed/unit1/lessons-08-10.ts',
    exportNames: ['LESSON_08_SEED_DATA', 'LESSON_09_SEED_DATA', 'LESSON_10_SEED_DATA'],
  },
  { relativePath: 'supabase/seed/unit1/lesson-11.ts', exportNames: ['LESSON_11_SEED_DATA'] },
];

const targetPath = path.resolve(
  process.cwd(),
  'lib/curriculum/generated/unit1-authored.ts',
);

function stripRuntimeBootstrap(source: string): string {
  const requireMainIndex = source.indexOf('if (require.main === module)');
  return requireMainIndex >= 0 ? source.slice(0, requireMainIndex) : source;
}

function createRequireStub() {
  return (specifier: string) => {
    if (specifier === 'dotenv') {
      return { config: () => ({}) };
    }

    if (specifier === 'drizzle-orm/postgres-js') {
      return { drizzle: () => ({}) };
    }

    if (specifier === 'postgres') {
      return () => ({});
    }

    if (specifier === 'drizzle-orm') {
      return {
        sql: (...parts: unknown[]) => parts,
      };
    }

    throw new Error(`Unsupported generator import: ${specifier}`);
  };
}

async function loadExports(relativePath: string): Promise<ExportMap> {
  const absolutePath = path.resolve(process.cwd(), relativePath);
  const source = stripRuntimeBootstrap(await fs.readFile(absolutePath, 'utf8'));
  const transpiled = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
      esModuleInterop: true,
    },
    fileName: absolutePath,
  });

  const moduleShim = { exports: {} as ExportMap };
  const context = vm.createContext({
    module: moduleShim,
    exports: moduleShim.exports,
    require: createRequireStub(),
    console,
    process: { env: process.env },
  });

  vm.runInContext(transpiled.outputText, context, {
    filename: absolutePath,
  });

  return moduleShim.exports;
}

async function main() {
  const authoredLessons: unknown[] = [];

  for (const sourceFile of SOURCE_EXPORTS) {
    const exports = await loadExports(sourceFile.relativePath);
    for (const exportName of sourceFile.exportNames) {
      if (!(exportName in exports)) {
        throw new Error(`Missing ${exportName} in ${sourceFile.relativePath}`);
      }
      authoredLessons.push(exports[exportName]);
    }
  }

  const header = `// Generated by scripts/generate-unit1-authored-module.ts
// Do not edit manually; regenerate from supabase/seed/unit1 source modules.

`;

  const fileSource = `${header}export const AUTHORED_UNIT_1_LESSONS = ${JSON.stringify(
    authoredLessons,
    null,
    2,
  )} as const;
`;

  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.writeFile(targetPath, fileSource, 'utf8');
  console.log(`Wrote ${path.relative(process.cwd(), targetPath)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
