export interface GlossaryTerm {
  slug: string;
  term_en: string;
  term_zh: string;
  def_en: string;
  def_zh: string;
  units: number[];
  topics: string[];
  synonyms: string[];
  related: string[];
}

export const GLOSSARY: GlossaryTerm[] = [
  {
    slug: 'accounting-equation',
    term_en: 'Accounting Equation',
    term_zh: '会计等式',
    def_en: 'The fundamental equation of accounting: Assets = Liabilities + Equity.',
    def_zh: '会计的基本等式：资产 = 负债 + 所有者权益。',
    units: [1],
    topics: ['foundations', 'financial-statements'],
    synonyms: ['balance-sheet-equation'],
    related: ['assets', 'liabilities', 'equity'],
  },
  {
    slug: 'assets',
    term_en: 'Assets',
    term_zh: '资产',
    def_en: 'Resources owned by a business that have future economic value.',
    def_zh: '企业拥有的具有未来经济价值的资源。',
    units: [1, 2, 3],
    topics: ['foundations', 'financial-statements'],
    synonyms: [],
    related: ['accounting-equation', 'liabilities', 'equity'],
  },
  {
    slug: 'liabilities',
    term_en: 'Liabilities',
    term_zh: '负债',
    def_en: 'Obligations of a business to pay others in the future.',
    def_zh: '企业未来向他人支付的义务。',
    units: [1, 2, 3],
    topics: ['foundations', 'financial-statements'],
    synonyms: [],
    related: ['accounting-equation', 'assets', 'equity'],
  },
  {
    slug: 'equity',
    term_en: 'Equity',
    term_zh: '所有者权益',
    def_en: 'The residual interest in the assets of a business after subtracting liabilities.',
    def_zh: '企业资产减去负债后的剩余权益。',
    units: [1, 2, 3],
    topics: ['foundations', 'financial-statements'],
    synonyms: ['owner\'s-equity', 'net-worth'],
    related: ['accounting-equation', 'assets', 'liabilities'],
  },
  {
    slug: 'break-even-point',
    term_en: 'Break-Even Point',
    term_zh: '盈亏平衡点',
    def_en: 'The level of sales where total revenue equals total costs, resulting in zero profit.',
    def_zh: '总收入等于总成本、利润为零的销售水平。',
    units: [5, 6],
    topics: ['cost-accounting', 'cvp-analysis'],
    synonyms: ['breakeven'],
    related: ['fixed-costs', 'variable-costs', 'contribution-margin'],
  },
  {
    slug: 'fixed-costs',
    term_en: 'Fixed Costs',
    term_zh: '固定成本',
    def_en: 'Costs that do not change with the level of production or sales.',
    def_zh: '不随生产或销售水平变化的成本。',
    units: [5, 6],
    topics: ['cost-accounting', 'cvp-analysis'],
    synonyms: ['overhead'],
    related: ['variable-costs', 'break-even-point'],
  },
  {
    slug: 'variable-costs',
    term_en: 'Variable Costs',
    term_zh: '可变成本',
    def_en: 'Costs that change directly with the level of production or sales.',
    def_zh: '随生产或销售水平直接变化的成本。',
    units: [5, 6],
    topics: ['cost-accounting', 'cvp-analysis'],
    synonyms: [],
    related: ['fixed-costs', 'break-even-point', 'contribution-margin'],
  },
  {
    slug: 'contribution-margin',
    term_en: 'Contribution Margin',
    term_zh: '边际贡献',
    def_en: 'Sales revenue minus variable costs, representing the amount available to cover fixed costs and contribute to profit.',
    def_zh: '销售收入减去可变成本，代表可用于覆盖固定成本和贡献利润的金额。',
    units: [5, 6],
    topics: ['cost-accounting', 'cvp-analysis'],
    synonyms: [],
    related: ['variable-costs', 'fixed-costs', 'break-even-point'],
  },
  {
    slug: 'depreciation',
    term_en: 'Depreciation',
    term_zh: '折旧',
    def_en: 'The allocation of the cost of a long-term asset over its useful life.',
    def_zh: '长期资产成本在其使用寿命内的分配。',
    units: [3, 4, 5],
    topics: ['financial-statements', 'cost-accounting'],
    synonyms: [],
    related: ['straight-line-depreciation', 'double-declining-balance'],
  },
  {
    slug: 'straight-line-depreciation',
    term_en: 'Straight-Line Depreciation',
    term_zh: '直线折旧法',
    def_en: 'Depreciation method that allocates equal amounts of an asset\'s cost to each period of its useful life.',
    def_zh: '将资产成本等额分配到其使用寿命内每个期间的折旧方法。',
    units: [3, 4, 5],
    topics: ['financial-statements', 'cost-accounting'],
    synonyms: [],
    related: ['depreciation', 'double-declining-balance'],
  },
  {
    slug: 'journal-entry',
    term_en: 'Journal Entry',
    term_zh: '日记账分录',
    def_en: 'A record of a business transaction in the accounting journal, showing debits and credits to specific accounts.',
    def_zh: '会计日记账中业务交易的记录，显示对特定账户的借方和贷方。',
    units: [2],
    topics: ['transactions', 'financial-statements'],
    synonyms: [],
    related: ['t-accounts', 'trial-balance'],
  },
  {
    slug: 't-accounts',
    term_en: 'T-Accounts',
    term_zh: 'T型账户',
    def_en: 'A visual representation of a general ledger account, shaped like a "T", with debits on the left and credits on the right.',
    def_zh: '总分类账账户的视觉表示，形状像“T”，借方在左侧，贷方在右侧。',
    units: [2],
    topics: ['transactions', 'financial-statements'],
    synonyms: ['ledger-accounts'],
    related: ['journal-entry', 'trial-balance'],
  },
  {
    slug: 'trial-balance',
    term_en: 'Trial Balance',
    term_zh: '试算平衡表',
    def_en: 'A list of all general ledger accounts and their balances at a specific point in time, used to verify that total debits equal total credits.',
    def_zh: '所有总分类账账户及其在特定时间点余额的列表，用于验证总借方等于总贷方。',
    units: [2],
    topics: ['transactions', 'financial-statements'],
    synonyms: [],
    related: ['journal-entry', 't-accounts'],
  },
  {
    slug: 'adjusting-entries',
    term_en: 'Adjusting Entries',
    term_zh: '调整分录',
    def_en: 'Journal entries made at the end of an accounting period to update account balances and ensure compliance with the matching principle.',
    def_zh: '会计期末编制的日记账分录，用于更新账户余额并确保符合配比原则。',
    units: [2],
    topics: ['transactions', 'financial-statements'],
    synonyms: [],
    related: ['journal-entry', 'closing-entries'],
  },
  {
    slug: 'closing-entries',
    term_en: 'Closing Entries',
    term_zh: '结账分录',
    def_en: 'Journal entries made at the end of an accounting period to transfer balances from temporary accounts to permanent accounts.',
    def_zh: '会计期末编制的日记账分录，用于将临时账户的余额转入永久账户。',
    units: [2],
    topics: ['transactions', 'financial-statements'],
    synonyms: [],
    related: ['journal-entry', 'adjusting-entries'],
  },
  {
    slug: 'income-statement',
    term_en: 'Income Statement',
    term_zh: '利润表',
    def_en: 'A financial statement that reports a company\'s revenues, expenses, and net income over a specific accounting period.',
    def_zh: '报告公司在特定会计期间的收入、费用和净利润的财务报表。',
    units: [2, 3, 7],
    topics: ['financial-statements'],
    synonyms: ['profit-and-loss-statement', 'statement-of-operations'],
    related: ['balance-sheet', 'cash-flow-statement'],
  },
  {
    slug: 'balance-sheet',
    term_en: 'Balance Sheet',
    term_zh: '资产负债表',
    def_en: 'A financial statement that reports a company\'s assets, liabilities, and equity at a specific point in time.',
    def_zh: '报告公司在特定时间点的资产、负债和所有者权益的财务报表。',
    units: [1, 2, 3, 7],
    topics: ['financial-statements'],
    synonyms: ['statement-of-financial-position'],
    related: ['income-statement', 'cash-flow-statement'],
  },
  {
    slug: 'cash-flow-statement',
    term_en: 'Cash Flow Statement',
    term_zh: '现金流量表',
    def_en: 'A financial statement that reports a company\'s cash inflows and outflows from operating, investing, and financing activities over a specific period.',
    def_zh: '报告公司在特定期间内经营、投资和融资活动的现金流入和流出的财务报表。',
    units: [2, 3],
    topics: ['financial-statements'],
    synonyms: ['statement-of-cash-flows'],
    related: ['income-statement', 'balance-sheet'],
  },
  {
    slug: 'revenue-growth',
    term_en: 'Revenue Growth',
    term_zh: '收入增长',
    def_en: 'The percentage increase in a company\'s revenue from one period to another, used to measure business expansion.',
    def_zh: '公司收入从一个期间到另一个期间的百分比增长，用于衡量业务扩张。',
    units: [7],
    topics: ['growth', 'valuation'],
    synonyms: ['sales-growth'],
    related: ['compound-growth', 'gross-margin'],
  },
  {
    slug: 'gross-margin',
    term_en: 'Gross Margin',
    term_zh: '毛利率',
    def_en: 'The percentage of revenue remaining after subtracting cost of goods sold, representing profitability before operating expenses.',
    def_zh: '减去销货成本后剩余收入的百分比，代表营业费用前的盈利能力。',
    units: [5, 6, 7],
    topics: ['cost-accounting', 'profitability'],
    synonyms: ['gross-profit-margin'],
    related: ['net-profit-margin', 'contribution-margin'],
  },
  {
    slug: 'net-profit-margin',
    term_en: 'Net Profit Margin',
    term_zh: '净利润率',
    def_en: 'The percentage of revenue remaining after subtracting all expenses, including cost of goods sold, operating expenses, interest, and taxes.',
    def_zh: '减去所有费用（包括销货成本、营业费用、利息和税）后剩余收入的百分比。',
    units: [5, 6, 7],
    topics: ['cost-accounting', 'profitability'],
    synonyms: ['net-margin'],
    related: ['gross-margin', 'roi'],
  },
  {
    slug: 'roi',
    term_en: 'Return on Investment (ROI)',
    term_zh: '投资回报率（ROI）',
    def_en: 'A performance measure used to evaluate the efficiency of an investment, calculated as net profit divided by the cost of investment.',
    def_zh: '用于评估投资效率的绩效指标，计算为净利润除以投资成本。',
    units: [7, 8],
    topics: ['valuation', 'investment'],
    synonyms: ['return-on-investment'],
    related: ['net-profit-margin', 'cost-of-capital'],
  },
  {
    slug: 'valuation-multiples',
    term_en: 'Valuation Multiples',
    term_zh: '估值倍数',
    def_en: 'Financial metrics used to compare the value of a company to a relevant financial metric, such as price-to-earnings (P/E) or enterprise value-to-EBITDA (EV/EBITDA).',
    def_zh: '用于将公司价值与相关财务指标（如市盈率（P/E）或企业价值与EBITDA之比（EV/EBITDA））进行比较的财务指标。',
    units: [7],
    topics: ['valuation'],
    synonyms: ['trading-multiples'],
    related: ['roi', 'compound-growth'],
  },
  {
    slug: 'compound-growth',
    term_en: 'Compound Growth',
    term_zh: '复合增长',
    def_en: 'Growth calculated on the initial principal and also on the accumulated interest or growth from previous periods.',
    def_zh: '基于初始本金以及前期累计利息或增长计算的增长。',
    units: [7],
    topics: ['growth', 'valuation'],
    synonyms: ['compound-interest'],
    related: ['revenue-growth', 'valuation-multiples'],
  },
  {
    slug: 'capital-structure',
    term_en: 'Capital Structure',
    term_zh: '资本结构',
    def_en: 'The mix of debt and equity financing used by a company to fund its operations and growth.',
    def_zh: '公司用于为其运营和增长提供资金的债务和股权融资的组合。',
    units: [8],
    topics: ['capital', 'financing'],
    synonyms: [],
    related: ['debt-financing', 'equity-financing'],
  },
  {
    slug: 'debt-financing',
    term_en: 'Debt Financing',
    term_zh: '债务融资',
    def_en: 'Raising capital by borrowing money from lenders, which must be repaid with interest over time.',
    def_zh: '通过向贷款人借款来筹集资金，必须随时间支付利息偿还。',
    units: [8],
    topics: ['capital', 'financing'],
    synonyms: ['borrowing'],
    related: ['equity-financing', 'cost-of-capital'],
  },
  {
    slug: 'equity-financing',
    term_en: 'Equity Financing',
    term_zh: '股权融资',
    def_en: 'Raising capital by selling ownership shares in the company, which does not require repayment but dilutes existing ownership.',
    def_zh: '通过出售公司的所有权股份来筹集资金，不需要偿还但会稀释现有所有权。',
    units: [8],
    topics: ['capital', 'financing'],
    synonyms: ['share-financing'],
    related: ['debt-financing', 'cost-of-capital'],
  },
  {
    slug: 'cost-of-capital',
    term_en: 'Cost of Capital',
    term_zh: '资本成本',
    def_en: 'The minimum return a company must earn on its investments to satisfy its investors and creditors.',
    def_zh: '公司必须在其投资上获得的最低回报，以满足其投资者和债权人。',
    units: [8],
    topics: ['capital', 'investment'],
    synonyms: ['hurdle-rate'],
    related: ['wacc', 'roi'],
  },
  {
    slug: 'wacc',
    term_en: 'Weighted Average Cost of Capital (WACC)',
    term_zh: '加权平均资本成本（WACC）',
    def_en: 'The average cost of a company\'s capital sources (debt and equity), weighted by their respective proportions in the capital structure.',
    def_zh: '公司资本来源（债务和股权）的平均成本，按其在资本结构中的各自比例加权。',
    units: [8],
    topics: ['capital', 'investment'],
    synonyms: ['weighted-average-cost-of-capital'],
    related: ['cost-of-capital', 'capital-structure'],
  },
  {
    slug: 'business-strategy',
    term_en: 'Business Strategy',
    term_zh: '商业战略',
    def_en: 'A set of long-term plans and actions designed to achieve a company\'s goals and competitive advantage in the market.',
    def_zh: '旨在实现公司目标和市场竞争优势的一套长期计划和行动。',
    units: [8],
    topics: ['strategy'],
    synonyms: ['corporate-strategy'],
    related: ['capital-structure', 'valuation-multiples'],
  },
];

export function getGlossaryTermBySlug(slug: string): GlossaryTerm | undefined {
  return GLOSSARY.find(term => term.slug === slug);
}

export function getGlossaryTermsByUnit(unitNumber: number): GlossaryTerm[] {
  return GLOSSARY.filter(term => term.units.includes(unitNumber));
}

export function getGlossaryTermsByTopic(topic: string): GlossaryTerm[] {
  return GLOSSARY.filter(term => term.topics.includes(topic));
}

export function getAllGlossaryTopics(): string[] {
  const topics = new Set<string>();
  GLOSSARY.forEach(term => term.topics.forEach(topic => topics.add(topic)));
  return Array.from(topics).sort();
}

export function getAllGlossaryUnits(): number[] {
  const units = new Set<number>();
  GLOSSARY.forEach(term => term.units.forEach(unit => units.add(unit)));
  return Array.from(units).sort((a, b) => a - b);
}
