/**
 * Module 1: Quadratic Functions and Complex Numbers
 *
 * Question bank for Module 1 practice tests.
 * 3+ questions per lesson covering the full module scope.
 */

import type { PracticeTestModuleConfig, PracticeTestQuestion } from '../types';
import { registerModuleConfig } from '../question-banks';

const MODULE_1_QUESTIONS: PracticeTestQuestion[] = [
  // Lesson 1-1: Graphing Quadratic Functions
  {
    id: 'm1-l1-q1',
    lessonId: 'lesson-1-1',
    lessonTitle: 'Graphing Quadratic Functions',
    prompt: 'What is the vertex of the quadratic function y = (x - 3)^2 + 2?',
    correctAnswer: '(3, 2)',
    distractors: ['(-3, 2)', '(3, -2)', '(0, 2)'],
    explanation: 'The vertex form y = a(x - h)^2 + k reveals the vertex at (h, k). Here h = 3 and k = 2.',
    objectiveTags: ['F-IF.7', 'F-BF.3'],
  },
  {
    id: 'm1-l1-q2',
    lessonId: 'lesson-1-1',
    lessonTitle: 'Graphing Quadratic Functions',
    prompt: 'Which transformation shifts y = x^2 left by 4 units?',
    correctAnswer: 'y = (x + 4)^2',
    distractors: ['y = x^2 + 4', 'y = (x - 4)^2', 'y = x^2 - 4'],
    explanation: 'Shifting left requires adding inside the parentheses: y = (x + 4)^2 shifts left by 4.',
    objectiveTags: ['F-BF.3'],
  },
  {
    id: 'm1-l1-q3',
    lessonId: 'lesson-1-1',
    lessonTitle: 'Graphing Quadratic Functions',
    prompt: 'What is the axis of symmetry for y = 2x^2 - 8x + 3?',
    correctAnswer: 'x = 2',
    distractors: ['x = 4', 'x = -2', 'x = 8'],
    explanation: 'Axis of symmetry: x = -b/(2a) = -(-8)/(2·2) = 8/4 = 2.',
    objectiveTags: ['F-IF.7'],
  },
  {
    id: 'm1-l1-q4',
    lessonId: 'lesson-1-1',
    lessonTitle: 'Graphing Quadratic Functions',
    prompt: 'The quadratic function y = -x^2 opens in which direction?',
    correctAnswer: 'Down',
    distractors: ['Up', 'Left', 'Right'],
    explanation: 'When the leading coefficient a is negative, the parabola opens downward.',
    objectiveTags: ['F-IF.7'],
  },

  // Lesson 1-2: Solving Quadratic Equations by Graphing
  {
    id: 'm1-l2-q1',
    lessonId: 'lesson-1-2',
    lessonTitle: 'Solving Quadratic Equations by Graphing',
    prompt: 'What are the x-intercepts of y = x^2 - 9?',
    correctAnswer: '(-3, 0) and (3, 0)',
    distractors: ['(0, -9)', '(0, 3) and (0, -3)', '(9, 0)'],
    explanation: 'Set y = 0: x^2 - 9 = 0, so x^2 = 9, giving x = ±3.',
    objectiveTags: ['A-SSE.3', 'F-IF.7'],
  },
  {
    id: 'm1-l2-q2',
    lessonId: 'lesson-1-2',
    lessonTitle: 'Solving Quadratic Equations by Graphing',
    prompt: 'Using the graph of y = x^2 - 4x + 3, what is the solution to x^2 - 4x + 3 = 0?',
    correctAnswer: 'x = 1 and x = 3',
    distractors: ['x = 1 only', 'x = -1 and x = -3', 'x = 4'],
    explanation: 'The x-intercepts of the graph give the solutions to the equation when y = 0.',
    objectiveTags: ['A-REI.4'],
  },
  {
    id: 'm1-l2-q3',
    lessonId: 'lesson-1-2',
    lessonTitle: 'Solving Quadratic Equations by Graphing',
    prompt: 'How many real solutions does the equation y = x^2 have when y = -4?',
    correctAnswer: '0 real solutions',
    distractors: ['1 real solution', '2 real solutions', 'Infinitely many solutions'],
    explanation: 'x^2 = -4 has no real solutions since squaring any real number is non-negative.',
    objectiveTags: ['A-SSE.3'],
  },
  {
    id: 'm1-l2-q4',
    lessonId: 'lesson-1-2',
    lessonTitle: 'Solving Quadratic Equations by Graphing',
    prompt: 'What does the y-intercept of y = 2x^2 - 5x + 1 represent in context?',
    correctAnswer: 'The value of y when x = 0',
    distractors: [
      'The maximum value of the function',
      'The solution to 2x^2 - 5x + 1 = 0',
      'The axis of symmetry',
    ],
    explanation: 'The y-intercept is the point where x = 0, giving y = 2(0)^2 - 5(0) + 1 = 1.',
    objectiveTags: ['F-IF.7'],
  },

  // Lesson 1-3: Complex Numbers
  {
    id: 'm1-l3-q1',
    lessonId: 'lesson-1-3',
    lessonTitle: 'Complex Numbers',
    prompt: 'What is i^2 equal to?',
    correctAnswer: '-1',
    distractors: ['1', 'i', '-i'],
    explanation: 'By definition, i is the imaginary unit where i^2 = -1.',
    objectiveTags: ['N-CN.1'],
  },
  {
    id: 'm1-l3-q2',
    lessonId: 'lesson-1-3',
    lessonTitle: 'Complex Numbers',
    prompt: 'Simplify: (3 + 2i) + (1 - 4i)',
    correctAnswer: '4 - 2i',
    distractors: ['4 + 2i', '3 - 8i', '2 - 2i'],
    explanation: 'Combine real parts: 3 + 1 = 4. Combine imaginary parts: 2i - 4i = -2i.',
    objectiveTags: ['N-CN.2'],
  },
  {
    id: 'm1-l3-q3',
    lessonId: 'lesson-1-3',
    lessonTitle: 'Complex Numbers',
    prompt: 'What is the product (2 + i)(2 - i)?',
    correctAnswer: '5',
    distractors: ['3', '4 - i', '4 + i'],
    explanation: '(2 + i)(2 - i) = 4 - 2i + 2i - i^2 = 4 + 1 = 5. This is a difference of squares.',
    objectiveTags: ['N-CN.2'],
  },
  {
    id: 'm1-l3-q4',
    lessonId: 'lesson-1-3',
    lessonTitle: 'Complex Numbers',
    prompt: 'Solve: x^2 + 9 = 0. What are the solutions?',
    correctAnswer: '3i and -3i',
    distractors: ['3 and -3', '9 and -9', '±√9'],
    explanation: 'x^2 = -9, so x = ±√(-9) = ±3i.',
    objectiveTags: ['N-CN.7'],
  },

  // Lesson 1-4: Solve Quadratic Equations by Factoring
  {
    id: 'm1-l4-q1',
    lessonId: 'lesson-1-4',
    lessonTitle: 'Solve Quadratic Equations by Factoring',
    prompt: 'Factor: x^2 + 5x + 6',
    correctAnswer: '(x + 2)(x + 3)',
    distractors: ['(x + 1)(x + 6)', '(x - 2)(x - 3)', '(x + 6)(x - 1)'],
    explanation: 'Find two numbers that multiply to 6 and add to 5: 2 and 3.',
    objectiveTags: ['A-SSE.2', 'A-APR.3'],
  },
  {
    id: 'm1-l4-q2',
    lessonId: 'lesson-1-4',
    lessonTitle: 'Solve Quadratic Equations by Factoring',
    prompt: 'Solve: x^2 - 4x - 12 = 0',
    correctAnswer: 'x = 6 or x = -2',
    distractors: ['x = 3 or x = -4', 'x = 2 or x = -6', 'x = 12 or x = -1'],
    explanation: 'Factor: (x - 6)(x + 2) = 0. Using zero product property: x - 6 = 0 or x + 2 = 0.',
    objectiveTags: ['A-REI.4'],
  },
  {
    id: 'm1-l4-q3',
    lessonId: 'lesson-1-4',
    lessonTitle: 'Solve Quadratic Equations by Factoring',
    prompt: 'Factor: 2x^2 + 7x + 3',
    correctAnswer: '(2x + 1)(x + 3)',
    distractors: ['(2x + 3)(x + 1)', '(2x - 1)(x - 3)', '(x + 1)(2x + 3)'],
    explanation: 'Find factors of 2·3=6 that sum to 7: 6 and 1. Rewrite and factor by grouping.',
    objectiveTags: ['A-SSE.2'],
  },
  {
    id: 'm1-l4-q4',
    lessonId: 'lesson-1-4',
    lessonTitle: 'Solve Quadratic Equations by Factoring',
    prompt: 'What method would you use to solve x^2 = 16?',
    correctAnswer: 'Square root property',
    distractors: ['Factoring', 'Quadratic formula', 'Completing the square'],
    explanation: 'This equation is already in the form where taking square roots is efficient: x = ±4.',
    objectiveTags: ['A-REI.4'],
  },

  // Lesson 1-5: Solving Quadratic Equations by Completing the Square
  {
    id: 'm1-l5-q1',
    lessonId: 'lesson-1-5',
    lessonTitle: 'Solving Quadratic Equations by Completing the Square',
    prompt: 'Complete the square for x^2 + 6x. What is the resulting expression?',
    correctAnswer: '(x + 3)^2 - 9',
    distractors: ['(x + 6)^2 - 36', '(x + 3)^2 + 9', '(x + 6)^2'],
    explanation: 'Take half of 6 (which is 3) and square it: 3^2 = 9. Then x^2 + 6x + 9 = (x + 3)^2.',
    objectiveTags: ['A-REI.4', 'A-SSE.3'],
  },
  {
    id: 'm1-l5-q2',
    lessonId: 'lesson-1-5',
    lessonTitle: 'Solving Quadratic Equations by Completing the Square',
    prompt: 'Solve by completing the square: x^2 + 4x - 5 = 0',
    correctAnswer: 'x = 1 or x = -5',
    distractors: ['x = 2 or x = -2', 'x = 5 or x = -1', 'x = 4 or x = -4'],
    explanation: 'Complete square: (x + 2)^2 - 4 - 5 = 0 → (x + 2)^2 = 9 → x + 2 = ±3.',
    objectiveTags: ['A-REI.4'],
  },
  {
    id: 'm1-l5-q3',
    lessonId: 'lesson-1-5',
    lessonTitle: 'Solving Quadratic Equations by Completing the Square',
    prompt: 'Convert y = x^2 + 8x + 3 to vertex form.',
    correctAnswer: 'y = (x + 4)^2 - 13',
    distractors: ['y = (x + 4)^2 - 19', 'y = (x + 8)^2 - 61', 'y = (x + 4)^2 + 13'],
    explanation: 'Complete square: (x + 4)^2 = x^2 + 8x + 16. So y = (x + 4)^2 - 13.',
    objectiveTags: ['F-BF.3'],
  },
  {
    id: 'm1-l5-q4',
    lessonId: 'lesson-1-5',
    lessonTitle: 'Solving Quadratic Equations by Completing the Square',
    prompt: 'When completing the square on 2x^2 + 8x + 5 = 0, what is the first step?',
    correctAnswer: 'Divide by 2 to make the coefficient of x^2 equal to 1',
    distractors: [
      'Add 5 to both sides',
      'Factor out 2 from all terms',
      'Take the square root of both sides',
    ],
    explanation: 'The leading coefficient must be 1 before completing the square, so divide everything by 2.',
    objectiveTags: ['A-REI.4'],
  },

  // Lesson 1-6: Using the Quadratic Formula and the Discriminant
  {
    id: 'm1-l6-q1',
    lessonId: 'lesson-1-6',
    lessonTitle: 'Using the Quadratic Formula and the Discriminant',
    prompt: 'Apply the quadratic formula to solve x^2 - 3x - 10 = 0. What are the solutions?',
    correctAnswer: 'x = 5 or x = -2',
    distractors: ['x = 2 or x = -5', 'x = 10 or x = -1', 'x = 3 or x = -10'],
    explanation: 'x = [3 ± √(9 + 40)]/2 = [3 ± √49]/2 = [3 ± 7]/2. So x = 5 or x = -2.',
    objectiveTags: ['A-REI.4'],
  },
  {
    id: 'm1-l6-q2',
    lessonId: 'lesson-1-6',
    lessonTitle: 'Using the Quadratic Formula and the Discriminant',
    prompt: 'What does the discriminant tell you about x^2 - 4x + 4 = 0?',
    correctAnswer: 'One repeated real solution',
    distractors: ['Two distinct real solutions', 'No real solutions', 'Two complex solutions'],
    explanation: 'Discriminant: b^2 - 4ac = 16 - 16 = 0. Zero discriminant means one repeated root.',
    objectiveTags: ['A-REI.4', 'N-CN.7'],
  },
  {
    id: 'm1-l6-q3',
    lessonId: 'lesson-1-6',
    lessonTitle: 'Using the Quadratic Formula and the Discriminant',
    prompt: 'Which value of the discriminant indicates two complex (non-real) solutions?',
    correctAnswer: 'Negative',
    distractors: ['Zero', 'Positive', 'Undefined'],
    explanation: 'A negative discriminant means √(b^2 - 4ac) is imaginary, giving complex solutions.',
    objectiveTags: ['N-CN.7'],
  },
  {
    id: 'm1-l6-q4',
    lessonId: 'lesson-1-6',
    lessonTitle: 'Using the Quadratic Formula and the Discriminant',
    prompt: 'Without solving, determine if 2x^2 + 3x + 5 = 0 has real solutions.',
    correctAnswer: 'No real solutions',
    distractors: ['Yes, two distinct real solutions', 'Yes, one repeated solution', 'Cannot be determined'],
    explanation: 'Discriminant: 9 - 4(2)(5) = 9 - 40 = -31 < 0. Negative discriminant means no real solutions.',
    objectiveTags: ['A-REI.4'],
  },

  // Lesson 1-7: Quadratic Inequalities
  {
    id: 'm1-l7-q1',
    lessonId: 'lesson-1-7',
    lessonTitle: 'Quadratic Inequalities',
    prompt: 'Solve: x^2 - 4x - 5 > 0',
    correctAnswer: 'x < -1 or x > 5',
    distractors: ['-1 < x < 5', 'x < -5 or x > 1', 'x > -1 and x < 5'],
    explanation: 'Factor: (x + 1)(x - 5) > 0. The solution is where the product is positive: x < -1 or x > 5.',
    objectiveTags: ['A-REI.4', 'A-CED.1'],
  },
  {
    id: 'm1-l7-q2',
    lessonId: 'lesson-1-7',
    lessonTitle: 'Quadratic Inequalities',
    prompt: 'Which graph represents the solution to y ≤ x^2 - 9?',
    correctAnswer: 'The region below or on the parabola y = x^2 - 9',
    distractors: [
      'The region above the parabola',
      'The region between the x-intercepts only',
      'The region to the right of the vertex',
    ],
    explanation: 'y ≤ means the y-values on or below the parabola are solutions.',
    objectiveTags: ['A-REI.4'],
  },
  {
    id: 'm1-l7-q3',
    lessonId: 'lesson-1-7',
    lessonTitle: 'Quadratic Inequalities',
    prompt: 'Solve: x^2 + 2x + 1 ≤ 0',
    correctAnswer: 'x = -1 only',
    distractors: ['x ≤ -1', 'x ≥ -1', 'All real numbers'],
    explanation: '(x + 1)^2 ≤ 0. A squared expression is always ≥ 0, so it equals 0 only when x = -1.',
    objectiveTags: ['A-REI.4'],
  },
  {
    id: 'm1-l7-q4',
    lessonId: 'lesson-1-7',
    lessonTitle: 'Quadratic Inequalities',
    prompt: 'Find the solution to x^2 < 16.',
    correctAnswer: '-4 < x < 4',
    distractors: ['x < -4 or x > 4', 'x < 4', 'x > -4'],
    explanation: 'Take square roots: -4 < x < 4. Remember to keep the inequality direction the same.',
    objectiveTags: ['A-REI.4'],
  },

  // Lesson 1-8: Solving Linear-Nonlinear Systems
  {
    id: 'm1-l8-q1',
    lessonId: 'lesson-1-8',
    lessonTitle: 'Solving Linear-Nonlinear Systems',
    prompt: 'How many intersection points does y = x^2 - 4 and y = x + 2 have?',
    correctAnswer: '2',
    distractors: ['0', '1', '3'],
    explanation: 'Set equal: x^2 - 4 = x + 2 → x^2 - x - 6 = 0 → (x - 3)(x + 2) = 0. Two solutions means two intersection points.',
    objectiveTags: ['A-REI.7'],
  },
  {
    id: 'm1-l8-q2',
    lessonId: 'lesson-1-8',
    lessonTitle: 'Solving Linear-Nonlinear Systems',
    prompt: 'Solve the system: y = x^2 and y = 4',
    correctAnswer: '(2, 4) and (-2, 4)',
    distractors: ['(4, 2) only', '(2, 4) only', '(0, 4) only'],
    explanation: 'Set x^2 = 4, so x = ±2. Both give y = 4.',
    objectiveTags: ['A-REI.7'],
  },
  {
    id: 'm1-l8-q3',
    lessonId: 'lesson-1-8',
    lessonTitle: 'Solving Linear-Nonlinear Systems',
    prompt: 'A line y = mx + b intersects y = x^2 at exactly one point. What must be true about m and b?',
    correctAnswer: 'The line is tangent to the parabola at its vertex',
    distractors: [
      'm must equal 0',
      'b must equal 0',
      'The line must be vertical',
    ],
    explanation: 'One intersection means the line is tangent, touching the parabola at exactly one point.',
    objectiveTags: ['A-REI.7', 'F-IF.7'],
  },
  {
    id: 'm1-l8-q4',
    lessonId: 'lesson-1-8',
    lessonTitle: 'Solving Linear-Nonlinear Systems',
    prompt: 'Solve: y = x + 4 and y = x^2 - 2x',
    correctAnswer: '(4, 8) and (-1, 3)',
    distractors: ['(2, 6) only', '(3, 7) only', '(8, 4) and (3, -1)'],
    explanation: 'Set equal: x + 4 = x^2 - 2x → 0 = x^2 - 3x - 4 → (x - 4)(x + 1) = 0. So x = 4 or x = -1.',
    objectiveTags: ['A-REI.7'],
  },
];

const MODULE_1_CONFIG: PracticeTestModuleConfig = {
  moduleNumber: 1,
  title: 'Quadratic Functions and Complex Numbers',
  description:
    'Explore quadratic functions, their graphs, and complex number operations. Master multiple solution methods including graphing, factoring, completing the square, and the quadratic formula.',
  lessons: [
    { lessonId: 'lesson-1-1', lessonNumber: 1, title: 'Graphing Quadratic Functions' },
    { lessonId: 'lesson-1-2', lessonNumber: 2, title: 'Solving Quadratic Equations by Graphing' },
    { lessonId: 'lesson-1-3', lessonNumber: 3, title: 'Complex Numbers' },
    { lessonId: 'lesson-1-4', lessonNumber: 4, title: 'Solve Quadratic Equations by Factoring' },
    {
      lessonId: 'lesson-1-5',
      lessonNumber: 5,
      title: 'Solving Quadratic Equations by Completing the Square',
    },
    {
      lessonId: 'lesson-1-6',
      lessonNumber: 6,
      title: 'Using the Quadratic Formula and the Discriminant',
    },
    { lessonId: 'lesson-1-7', lessonNumber: 7, title: 'Quadratic Inequalities' },
    { lessonId: 'lesson-1-8', lessonNumber: 8, title: 'Solving Linear-Nonlinear Systems' },
  ],
  questions: MODULE_1_QUESTIONS,
  phaseContent: {
    introduction: {
      heading: 'Module 1 Practice Test',
      body: 'Quadratic Functions and Complex Numbers. Select the lessons you want to include and choose how many questions to answer.',
    },
    assessment: {
      questionNumberLabel: 'Question {current} of {total}',
      correctFeedback: 'Correct!',
      incorrectFeedback: 'Incorrect. See the explanation below.',
      continueButton: 'Continue',
    },
    closing: {
      heading: 'Test Complete!',
      scoreLabel: 'Your Score',
      perLessonBreakdownLabel: 'Breakdown by Lesson',
      retryButton: 'Retry Test',
      backToModulesButton: 'Back to Modules',
    },
  },
  messaging: {
    selectLessons: 'Select lessons to include in this practice test:',
    questionCountLabel: 'Number of questions:',
    questionCountPlaceholder: '10',
    startTest: 'Start Test',
    noQuestionsAvailable:
      'No questions available for the selected lessons. Please select at least one lesson.',
  },
};

registerModuleConfig(MODULE_1_CONFIG);

export default MODULE_1_CONFIG;