/**
 * Module 9: Trigonometric Functions
 *
 * Question bank for Module 9 practice tests.
 * 4 questions per lesson covering trigonometric functions and graphs.
 */

import type { PracticeTestModuleConfig, PracticeTestQuestion } from '../types';
import { registerModuleConfig } from '../question-banks';

const MODULE_9_QUESTIONS: PracticeTestQuestion[] = [
  // Lesson 9-1: Angles and Angle Measure
  {
    id: 'm9-l1-q1',
    lessonId: 'lesson-9-1',
    lessonTitle: 'Angles and Angle Measure',
    prompt: 'Convert 150° to radians.',
    correctAnswer: '5π/6',
    distractors: ['3π/4', '2π/3', '7π/6'],
    explanation: 'Multiply by π/180: 150 × π/180 = 15π/18 = 5π/6.',
    objectiveTags: ['F-TF.1'],
  },
  {
    id: 'm9-l1-q2',
    lessonId: 'lesson-9-1',
    lessonTitle: 'Angles and Angle Measure',
    prompt: 'Which angle is coterminal with -π/4?',
    correctAnswer: '7π/4',
    distractors: ['3π/4', '5π/4', 'π/4'],
    explanation: 'Add 2π to -π/4: -π/4 + 8π/4 = 7π/4.',
    objectiveTags: ['F-TF.1'],
  },
  {
    id: 'm9-l1-q3',
    lessonId: 'lesson-9-1',
    lessonTitle: 'Angles and Angle Measure',
    prompt: 'What is the reference angle for 210°?',
    correctAnswer: '30°',
    distractors: ['60°', '45°', '210°'],
    explanation: '210° is in Quadrant III. Reference angle = 210° - 180° = 30°.',
    objectiveTags: ['F-TF.2'],
  },
  {
    id: 'm9-l1-q4',
    lessonId: 'lesson-9-1',
    lessonTitle: 'Angles and Angle Measure',
    prompt: 'Find the arc length intercepted by a central angle of π/3 radians in a circle of radius 6.',
    correctAnswer: '2π',
    distractors: ['3π', 'π', '4π'],
    explanation: 'Arc length s = rθ = 6 × π/3 = 2π.',
    objectiveTags: ['G-C.5'],
  },

  // Lesson 9-2: Trigonometric Functions of General Angles
  {
    id: 'm9-l2-q1',
    lessonId: 'lesson-9-2',
    lessonTitle: 'Trigonometric Functions of General Angles',
    prompt: 'What is the exact value of sin(300°)?',
    correctAnswer: '-√3/2',
    distractors: ['√3/2', '-1/2', '1/2'],
    explanation: '300° is in Quadrant IV with reference angle 60°. Sine is negative in QIV, so sin(300°) = -√3/2.',
    objectiveTags: ['F-TF.2', 'G-SRT.6'],
  },
  {
    id: 'm9-l2-q2',
    lessonId: 'lesson-9-2',
    lessonTitle: 'Trigonometric Functions of General Angles',
    prompt: 'In which quadrant is cos θ < 0 and sin θ > 0?',
    correctAnswer: 'Quadrant II',
    distractors: ['Quadrant I', 'Quadrant III', 'Quadrant IV'],
    explanation: 'Cosine is negative in QII and QIII; sine is positive in QI and QII. Both conditions are met in QII.',
    objectiveTags: ['F-TF.2'],
  },
  {
    id: 'm9-l2-q3',
    lessonId: 'lesson-9-2',
    lessonTitle: 'Trigonometric Functions of General Angles',
    prompt: 'Evaluate tan(5π/6).',
    correctAnswer: '-√3/3',
    distractors: ['√3/3', '-1', '√3'],
    explanation: 'Reference angle is π/6. Tangent is negative in QII, so tan(5π/6) = -tan(π/6) = -√3/3.',
    objectiveTags: ['F-TF.2', 'G-SRT.6'],
  },
  {
    id: 'm9-l2-q4',
    lessonId: 'lesson-9-2',
    lessonTitle: 'Trigonometric Functions of General Angles',
    prompt: 'If the terminal side of angle θ passes through the point (-3, 4), what is cos θ?',
    correctAnswer: '-3/5',
    distractors: ['4/5', '-4/3', '3/5'],
    explanation: 'r = √((-3)^2 + 4^2) = 5. cos θ = x/r = -3/5.',
    objectiveTags: ['G-SRT.6'],
  },

  // Lesson 9-3: Circular and Periodic Functions
  {
    id: 'm9-l3-q1',
    lessonId: 'lesson-9-3',
    lessonTitle: 'Circular and Periodic Functions',
    prompt: 'What is the period of the function f(x) = sin(4x)?',
    correctAnswer: 'π/2',
    distractors: ['4π', '2π', 'π/4'],
    explanation: 'Period = 2π/|b| = 2π/4 = π/2.',
    objectiveTags: ['F-TF.5'],
  },
  {
    id: 'm9-l3-q2',
    lessonId: 'lesson-9-3',
    lessonTitle: 'Circular and Periodic Functions',
    prompt: 'Which trigonometric function is even?',
    correctAnswer: 'cosine',
    distractors: ['sine', 'tangent', 'cosecant'],
    explanation: 'Cosine is even because cos(-x) = cos(x). Sine, tangent, and cosecant are odd.',
    objectiveTags: ['F-TF.4'],
  },
  {
    id: 'm9-l3-q3',
    lessonId: 'lesson-9-3',
    lessonTitle: 'Circular and Periodic Functions',
    prompt: 'A point moves around a unit circle with angular speed π/6 rad/s. How long does it take to complete one revolution?',
    correctAnswer: '12 seconds',
    distractors: ['6 seconds', '2 seconds', '1/12 second'],
    explanation: 'One revolution is 2π radians. Time = 2π ÷ (π/6) = 12 seconds.',
    objectiveTags: ['F-TF.1'],
  },
  {
    id: 'm9-l3-q4',
    lessonId: 'lesson-9-3',
    lessonTitle: 'Circular and Periodic Functions',
    prompt: 'What is the value of sec(π)?',
    correctAnswer: '-1',
    distractors: ['1', '0', 'undefined'],
    explanation: 'sec(π) = 1/cos(π) = 1/(-1) = -1.',
    objectiveTags: ['F-TF.2'],
  },

  // Lesson 9-4: Graphing Sine and Cosine Functions
  {
    id: 'm9-l4-q1',
    lessonId: 'lesson-9-4',
    lessonTitle: 'Graphing Sine and Cosine Functions',
    prompt: 'What is the amplitude of y = 3 sin(x)?',
    correctAnswer: '3',
    distractors: ['1', '6', '3/2'],
    explanation: 'Amplitude is |A| = |3| = 3.',
    objectiveTags: ['F-TF.5'],
  },
  {
    id: 'm9-l4-q2',
    lessonId: 'lesson-9-4',
    lessonTitle: 'Graphing Sine and Cosine Functions',
    prompt: 'What is the period of y = cos(2x)?',
    correctAnswer: 'π',
    distractors: ['2π', 'π/2', '4π'],
    explanation: 'Period = 2π/|b| = 2π/2 = π.',
    objectiveTags: ['F-TF.5'],
  },
  {
    id: 'm9-l4-q3',
    lessonId: 'lesson-9-4',
    lessonTitle: 'Graphing Sine and Cosine Functions',
    prompt: 'What is the maximum value of y = -2 cos(x) + 1?',
    correctAnswer: '3',
    distractors: ['1', '-1', '-2'],
    explanation: 'The maximum of -2 cos(x) is 2 (when cos(x) = -1). So maximum y = 2 + 1 = 3.',
    objectiveTags: ['F-IF.7', 'F-TF.5'],
  },
  {
    id: 'm9-l4-q4',
    lessonId: 'lesson-9-4',
    lessonTitle: 'Graphing Sine and Cosine Functions',
    prompt: 'Which function has a range of [-4, 4]?',
    correctAnswer: 'y = 4 sin(x)',
    distractors: ['y = sin(4x)', 'y = sin(x) + 4', 'y = 4 + sin(x)'],
    explanation: 'Amplitude 4 means the sine wave oscillates between -4 and 4.',
    objectiveTags: ['F-IF.7'],
  },

  // Lesson 9-5: Graphing Other Trigonometric Functions
  {
    id: 'm9-l5-q1',
    lessonId: 'lesson-9-5',
    lessonTitle: 'Graphing Other Trigonometric Functions',
    prompt: 'What is the period of y = tan(x)?',
    correctAnswer: 'π',
    distractors: ['2π', 'π/2', '1'],
    explanation: 'The tangent function repeats every π radians.',
    objectiveTags: ['F-TF.5'],
  },
  {
    id: 'm9-l5-q2',
    lessonId: 'lesson-9-5',
    lessonTitle: 'Graphing Other Trigonometric Functions',
    prompt: 'Where does y = tan(x) have a vertical asymptote?',
    correctAnswer: 'x = π/2',
    distractors: ['x = 0', 'x = π', 'x = 2π'],
    explanation: 'tan(x) = sin(x)/cos(x) is undefined where cos(x) = 0, which occurs at x = π/2 + nπ.',
    objectiveTags: ['F-IF.7'],
  },
  {
    id: 'm9-l5-q3',
    lessonId: 'lesson-9-5',
    lessonTitle: 'Graphing Other Trigonometric Functions',
    prompt: 'What is the range of y = csc(x)?',
    correctAnswer: '(-∞, -1] ∪ [1, ∞)',
    distractors: ['[-1, 1]', '(-∞, ∞)', '[1, ∞)'],
    explanation: 'csc(x) = 1/sin(x). Since sin(x) is between -1 and 1, csc(x) is ≤ -1 or ≥ 1.',
    objectiveTags: ['F-IF.7'],
  },
  {
    id: 'm9-l5-q4',
    lessonId: 'lesson-9-5',
    lessonTitle: 'Graphing Other Trigonometric Functions',
    prompt: 'Which function has vertical asymptotes at x = nπ for all integers n?',
    correctAnswer: 'y = csc(x)',
    distractors: ['y = sec(x)', 'y = tan(x)', 'y = cot(x)'],
    explanation: 'csc(x) = 1/sin(x), so it has asymptotes where sin(x) = 0, which is x = nπ.',
    objectiveTags: ['F-IF.7'],
  },

  // Lesson 9-6: Translations of Trigonometric Graphs
  {
    id: 'm9-l6-q1',
    lessonId: 'lesson-9-6',
    lessonTitle: 'Translations of Trigonometric Graphs',
    prompt: 'What is the phase shift of y = sin(x - π/3)?',
    correctAnswer: 'π/3 to the right',
    distractors: ['π/3 to the left', 'π/3 up', 'π/3 down'],
    explanation: 'y = sin(x - c) shifts right by c. Here c = π/3, so the shift is π/3 to the right.',
    objectiveTags: ['F-BF.3'],
  },
  {
    id: 'm9-l6-q2',
    lessonId: 'lesson-9-6',
    lessonTitle: 'Translations of Trigonometric Graphs',
    prompt: 'What is the vertical shift of y = 2 cos(x) + 3?',
    correctAnswer: '3 units up',
    distractors: ['2 units up', '3 units down', '2 units down'],
    explanation: 'The +3 outside the cosine function shifts the entire graph up by 3 units.',
    objectiveTags: ['F-BF.3'],
  },
  {
    id: 'm9-l6-q3',
    lessonId: 'lesson-9-6',
    lessonTitle: 'Translations of Trigonometric Graphs',
    prompt: 'Which equation represents a sine graph with amplitude 2, period π, and shifted left by π/4?',
    correctAnswer: 'y = 2 sin(2(x + π/4))',
    distractors: ['y = 2 sin(2x - π/4)', 'y = 2 sin(x/2 + π/4)', 'y = 2 sin(2x) + π/4'],
    explanation: 'Period π means b = 2. Shift left by π/4 means replace x with (x + π/4).',
    objectiveTags: ['F-BF.3', 'F-TF.5'],
  },
  {
    id: 'm9-l6-q4',
    lessonId: 'lesson-9-6',
    lessonTitle: 'Translations of Trigonometric Graphs',
    prompt: 'Describe the transformation from y = cos(x) to y = -cos(x) + 1.',
    correctAnswer: 'Reflect over the x-axis and shift up 1 unit',
    distractors: ['Reflect over the y-axis and shift up 1 unit', 'Shift down 1 unit and reflect over x-axis', 'Shift left 1 unit and reflect over y-axis'],
    explanation: 'The negative reflects over the x-axis; the +1 shifts the graph up 1 unit.',
    objectiveTags: ['F-BF.3'],
  },

  // Lesson 9-7: Inverse Trigonometric Functions
  {
    id: 'm9-l7-q1',
    lessonId: 'lesson-9-7',
    lessonTitle: 'Inverse Trigonometric Functions',
    prompt: 'What is the domain of y = sin⁻¹(x)?',
    correctAnswer: '[-1, 1]',
    distractors: ['[-π/2, π/2]', '(-∞, ∞)', '[0, π]'],
    explanation: 'The inverse sine function is defined only for x-values between -1 and 1, inclusive.',
    objectiveTags: ['F-TF.6'],
  },
  {
    id: 'm9-l7-q2',
    lessonId: 'lesson-9-7',
    lessonTitle: 'Inverse Trigonometric Functions',
    prompt: 'Evaluate sin⁻¹(√2/2).',
    correctAnswer: 'π/4',
    distractors: ['π/2', 'π/3', '-π/4'],
    explanation: 'sin(π/4) = √2/2, and π/4 is in the principal range [-π/2, π/2].',
    objectiveTags: ['F-TF.6'],
  },
  {
    id: 'm9-l7-q3',
    lessonId: 'lesson-9-7',
    lessonTitle: 'Inverse Trigonometric Functions',
    prompt: 'What is the principal value range of y = tan⁻¹(x)?',
    correctAnswer: '(-π/2, π/2)',
    distractors: ['[0, π]', '[-π/2, π/2]', '(-∞, ∞)'],
    explanation: 'The range of inverse tangent is all real angles between -π/2 and π/2, not including the endpoints.',
    objectiveTags: ['F-TF.6'],
  },
  {
    id: 'm9-l7-q4',
    lessonId: 'lesson-9-7',
    lessonTitle: 'Inverse Trigonometric Functions',
    prompt: 'Evaluate cos⁻¹(cos(5π/4)).',
    correctAnswer: '3π/4',
    distractors: ['5π/4', 'π/4', '-π/4'],
    explanation: 'cos⁻¹ returns values in [0, π]. Since cos(5π/4) = -√2/2, the angle in [0, π] with this cosine is 3π/4.',
    objectiveTags: ['F-TF.6'],
  },
];

const MODULE_9_CONFIG: PracticeTestModuleConfig = {
  moduleNumber: 9,
  title: 'Trigonometric Functions',
  description:
    'Explore angles, the unit circle, and trigonometric functions. Master graphing sine, cosine, and other trig functions, along with transformations and inverse trig functions.',
  lessons: [
    { lessonId: 'lesson-9-1', lessonNumber: 1, title: 'Angles and Angle Measure' },
    { lessonId: 'lesson-9-2', lessonNumber: 2, title: 'Trigonometric Functions of General Angles' },
    { lessonId: 'lesson-9-3', lessonNumber: 3, title: 'Circular and Periodic Functions' },
    { lessonId: 'lesson-9-4', lessonNumber: 4, title: 'Graphing Sine and Cosine Functions' },
    { lessonId: 'lesson-9-5', lessonNumber: 5, title: 'Graphing Other Trigonometric Functions' },
    { lessonId: 'lesson-9-6', lessonNumber: 6, title: 'Translations of Trigonometric Graphs' },
    { lessonId: 'lesson-9-7', lessonNumber: 7, title: 'Inverse Trigonometric Functions' },
  ],
  questions: MODULE_9_QUESTIONS,
  phaseContent: {
    introduction: {
      heading: 'Module 9 Practice Test',
      body: 'Trigonometric Functions. Select the lessons you want to include and choose how many questions to answer.',
    },
    assessment: {
      questionNumberLabel: 'Question {current} of {total}',
      correctFeedback: 'Correct!',
      incorrectFeedback: 'Incorrect. See the explanation below.',
      continueButton: 'Continue',
    },
    closing: {
      heading: 'Test Complete!',
      scoreLabel: 'Your Score',
      perLessonBreakdownLabel: 'Breakdown by Lesson',
      retryButton: 'Retry Test',
      backToModulesButton: 'Back to Modules',
    },
  },
  messaging: {
    selectLessons: 'Select lessons to include in this practice test:',
    questionCountLabel: 'Number of questions:',
    questionCountPlaceholder: '10',
    startTest: 'Start Test',
    noQuestionsAvailable:
      'No questions available for the selected lessons. Please select at least one lesson.',
  },
};

registerModuleConfig(MODULE_9_CONFIG);

export default MODULE_9_CONFIG;
