export const units = [
  { number: 1, title: "Relationships in Triangles" },
  { number: 2, title: "Quadrilaterals" },
  { number: 3, title: "Similarity" },
  { number: 4, title: "Right Triangles & Trigonometry" },
  { number: 5, title: "Circles" },
  { number: 6, title: "Measurement" },
  { number: 7, title: "Probability" },
  { number: 8, title: "Relations and Functions" },
  { number: 9, title: "Linear Equations, Inequalities & Systems" },
  { number: 10, title: "Exponents and Roots" },
  { number: 11, title: "Polynomials" },
  { number: 12, title: "Quadratic Functions" },
  { number: 13, title: "Trigonometric Identities & Equations" },
];

export const lessonSlugs: Record<number, Array<{ slug: string; title: string }>> = {
  1: [
    { slug: "1-1-classifying-triangles", title: "Classifying Triangles" },
    { slug: "1-2-triangle-angle-relationships", title: "Triangle Angle Relationships" },
    { slug: "1-3-triangle-inequality-theorem", title: "Triangle Inequality Theorem" },
    { slug: "1-4-congruence-criteria", title: "Congruence Criteria (SSS, SAS, ASA, AAS, HL)" },
    { slug: "1-5-proving-triangle-congruence", title: "Proving Triangle Congruence" },
    { slug: "1-6-isosceles-equilateral-properties", title: "Isosceles & Equilateral Triangle Properties" },
  ],
  2: [
    { slug: "2-1-polygon-basics-angle-sums", title: "Polygon Basics & Angle Sums" },
    { slug: "2-2-parallelogram-properties", title: "Parallelogram Properties" },
    { slug: "2-3-special-parallelograms", title: "Special Parallelograms (Rectangle, Rhombus, Square)" },
    { slug: "2-4-trapezoids", title: "Trapezoids and Isosceles Trapezoids" },
    { slug: "2-5-coordinate-proofs-quadrilaterals", title: "Coordinate Proofs with Quadrilaterals" },
  ],
  3: [
    { slug: "3-1-similar-figures-scale-factors", title: "Similar Figures and Scale Factors" },
    { slug: "3-2-triangle-similarity", title: "Triangle Similarity (AA, SAS, SSS)" },
    { slug: "3-3-proportions-indirect-measurement", title: "Proportions and Indirect Measurement" },
    { slug: "3-4-similarity-proofs", title: "Similarity Proofs" },
    { slug: "3-5-applications-similarity", title: "Applications of Similarity" },
  ],
  4: [
    { slug: "4-1-pythagorean-theorem", title: "Pythagorean Theorem" },
    { slug: "4-2-special-right-triangles", title: "Special Right Triangles (30-60-90, 45-45-90)" },
    { slug: "4-3-intro-sin-cos-tan", title: "Introduction to Sine, Cosine, Tangent" },
    { slug: "4-4-solving-right-triangles", title: "Solving Right Triangles" },
    { slug: "4-5-law-of-sines", title: "Law of Sines" },
    { slug: "4-6-law-of-cosines", title: "Law of Cosines" },
  ],
  5: [
    { slug: "5-1-circle-vocabulary-properties", title: "Circle Vocabulary and Basic Properties" },
    { slug: "5-2-angles-in-circles", title: "Angles in Circles (Central, Inscribed)" },
    { slug: "5-3-arcs-and-chords", title: "Arcs and Chords" },
    { slug: "5-4-tangents-and-secants", title: "Tangents and Secants" },
    { slug: "5-5-equations-of-circles", title: "Equations of Circles (Coordinate Plane)" },
  ],
  6: [
    { slug: "6-1-area-of-polygons", title: "Area of Polygons" },
    { slug: "6-2-surface-area-3d", title: "Surface Area of 3D Figures" },
    { slug: "6-3-volume-prisms-cylinders", title: "Volume of Prisms and Cylinders" },
    { slug: "6-4-volume-cones-spheres", title: "Volume of Cones and Spheres" },
    { slug: "6-5-cross-sections-composite", title: "Cross-Sections and Composite Solids" },
  ],
  7: [
    { slug: "7-1-basic-probability", title: "Basic Probability Concepts" },
    { slug: "7-2-counting-principle", title: "Counting Principle" },
    { slug: "7-3-permutations", title: "Permutations" },
    { slug: "7-4-combinations", title: "Combinations" },
    { slug: "7-5-compound-probability", title: "Compound Probability" },
    { slug: "7-6-fair-decisions-expected-value", title: "Fair Decisions and Expected Value" },
  ],
  8: [
    { slug: "8-1-relations-vs-functions", title: "Relations vs. Functions" },
    { slug: "8-2-domain-and-range", title: "Domain and Range" },
    { slug: "8-3-function-notation", title: "Function Notation" },
    { slug: "8-4-linear-nonlinear-functions", title: "Linear and Nonlinear Functions" },
    { slug: "8-5-function-transformations", title: "Function Transformations" },
    { slug: "8-6-comparing-functions", title: "Comparing Functions" },
  ],
  9: [
    { slug: "9-1-solving-linear-equations", title: "Solving Linear Equations" },
    { slug: "9-2-graphing-linear-equations", title: "Graphing Linear Equations" },
    { slug: "9-3-linear-inequalities", title: "Linear Inequalities" },
    { slug: "9-4-systems-of-equations", title: "Systems of Equations (Graphing, Substitution, Elimination)" },
    { slug: "9-5-systems-of-inequalities", title: "Systems of Inequalities" },
  ],
  10: [
    { slug: "10-1-laws-of-exponents", title: "Laws of Exponents" },
    { slug: "10-2-negative-rational-exponents", title: "Negative and Rational Exponents" },
    { slug: "10-3-scientific-notation", title: "Scientific Notation" },
    { slug: "10-4-radical-expressions", title: "Radical Expressions" },
    { slug: "10-5-solving-radical-equations", title: "Solving Radical Equations" },
  ],
  11: [
    { slug: "11-1-polynomial-vocabulary", title: "Polynomial Vocabulary and Classification" },
    { slug: "11-2-adding-subtracting-polynomials", title: "Adding and Subtracting Polynomials" },
    { slug: "11-3-multiplying-polynomials", title: "Multiplying Polynomials" },
    { slug: "11-4-special-products", title: "Special Products" },
    { slug: "11-5-factoring-techniques", title: "Factoring Techniques" },
    { slug: "11-6-solving-polynomial-equations", title: "Solving Polynomial Equations" },
  ],
  12: [
    { slug: "12-1-graphing-quadratics", title: "Graphing Quadratics (Vertex Form)" },
    { slug: "12-2-factoring-quadratics", title: "Factoring Quadratics" },
    { slug: "12-3-completing-the-square", title: "Completing the Square" },
    { slug: "12-4-quadratic-formula", title: "Quadratic Formula" },
    { slug: "12-5-quadratic-applications", title: "Applications of Quadratic Models" },
  ],
  13: [
    { slug: "13-1-fundamental-trig-identities", title: "Fundamental Trig Identities" },
    { slug: "13-2-pythagorean-identities", title: "Pythagorean Identities" },
    { slug: "13-3-sum-difference-identities", title: "Sum and Difference Identities" },
    { slug: "13-4-double-half-angle-identities", title: "Double-Angle and Half-Angle Identities" },
    { slug: "13-5-solving-trig-equations", title: "Solving Trigonometric Equations" },
  ],
};
